FROM elixir:1.20.1-alpine

# Install development dependencies
RUN apk add --no-cache build-base git inotify-tools curl nodejs npm

WORKDIR /app

# Install hex and rebar
RUN mix local.hex --force && \
    mix local.rebar --force

# Copy mix files for dependency installation
COPY mix.exs mix.lock ./
RUN mix deps.get

# Copy application files
COPY . .

# Compile dependencies and prebuild static assets
RUN mix deps.compile && mix assets.setup && mix assets.build

# Expose the port
EXPOSE 4001

# Run the application in development mode
CMD ["mix", "run", "--no-halt"]
