// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.12.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.12.0';

  @override
  int get rustContentHash => -1482817765;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'mydia_player_p2p',
    ioDirectory: 'rust/mydia_player_p2p/target/release/',
    webPrefix: 'pkg/',
    wasmBindgenName: 'wasm_bindgen',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<void> crateP2PHostDial(
      {required P2PHost that, required String endpointAddrJson});

  Stream<String> crateP2PHostEventStream({required P2PHost that});

  Future<FlutterNetworkStats> crateP2PHostGetNetworkStats(
      {required P2PHost that});

  Future<String> crateP2PHostGetNodeAddr({required P2PHost that});

  (P2PHost, String) crateP2PHostInit(
      {String? relayUrl, Uint8List? keypairBytes});

  Future<FlutterGraphQLResponse> crateP2PHostSendGraphqlRequest(
      {required P2PHost that,
      required String peer,
      required FlutterGraphQLRequest req});

  Future<FlutterHlsResponse> crateP2PHostSendHlsRequest(
      {required P2PHost that,
      required String peer,
      required FlutterHlsRequest req});

  Stream<FlutterHlsStreamEvent> crateP2PHostSendHlsRequestStreaming(
      {required P2PHost that,
      required String peer,
      required FlutterHlsRequest req});

  Future<FlutterPairingResponse> crateP2PHostSendPairingRequest(
      {required P2PHost that,
      required String peer,
      required FlutterPairingRequest req});

  Future<void> crateInitApp();

  RustArcIncrementStrongCountFnType get rust_arc_increment_strong_count_P2PHost;

  RustArcDecrementStrongCountFnType get rust_arc_decrement_strong_count_P2PHost;

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_P2PHostPtr;
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<void> crateP2PHostDial(
      {required P2PHost that, required String endpointAddrJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(endpointAddrJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 1, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostDialConstMeta,
      argValues: [that, endpointAddrJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostDialConstMeta => const TaskConstMeta(
        debugName: "P2PHost_dial",
        argNames: ["that", "endpointAddrJson"],
      );

  @override
  Stream<String> crateP2PHostEventStream({required P2PHost that}) {
    final sink = RustStreamSink<String>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_StreamSink_String_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 2, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostEventStreamConstMeta,
      argValues: [that, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateP2PHostEventStreamConstMeta => const TaskConstMeta(
        debugName: "P2PHost_event_stream",
        argNames: ["that", "sink"],
      );

  @override
  Future<FlutterNetworkStats> crateP2PHostGetNetworkStats(
      {required P2PHost that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_flutter_network_stats,
        decodeErrorData: null,
      ),
      constMeta: kCrateP2PHostGetNetworkStatsConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostGetNetworkStatsConstMeta =>
      const TaskConstMeta(
        debugName: "P2PHost_get_network_stats",
        argNames: ["that"],
      );

  @override
  Future<String> crateP2PHostGetNodeAddr({required P2PHost that}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateP2PHostGetNodeAddrConstMeta,
      argValues: [that],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostGetNodeAddrConstMeta => const TaskConstMeta(
        debugName: "P2PHost_get_node_addr",
        argNames: ["that"],
      );

  @override
  (P2PHost, String) crateP2PHostInit(
      {String? relayUrl, Uint8List? keypairBytes}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_opt_String(relayUrl, serializer);
        sse_encode_opt_list_prim_u_8_strict(keypairBytes, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData:
            sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string,
        decodeErrorData: null,
      ),
      constMeta: kCrateP2PHostInitConstMeta,
      argValues: [relayUrl, keypairBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostInitConstMeta => const TaskConstMeta(
        debugName: "P2PHost_init",
        argNames: ["relayUrl", "keypairBytes"],
      );

  @override
  Future<FlutterGraphQLResponse> crateP2PHostSendGraphqlRequest(
      {required P2PHost that,
      required String peer,
      required FlutterGraphQLRequest req}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_box_autoadd_flutter_graph_ql_request(req, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_flutter_graph_ql_response,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostSendGraphqlRequestConstMeta,
      argValues: [that, peer, req],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostSendGraphqlRequestConstMeta =>
      const TaskConstMeta(
        debugName: "P2PHost_send_graphql_request",
        argNames: ["that", "peer", "req"],
      );

  @override
  Future<FlutterHlsResponse> crateP2PHostSendHlsRequest(
      {required P2PHost that,
      required String peer,
      required FlutterHlsRequest req}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_box_autoadd_flutter_hls_request(req, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_flutter_hls_response,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostSendHlsRequestConstMeta,
      argValues: [that, peer, req],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostSendHlsRequestConstMeta => const TaskConstMeta(
        debugName: "P2PHost_send_hls_request",
        argNames: ["that", "peer", "req"],
      );

  @override
  Stream<FlutterHlsStreamEvent> crateP2PHostSendHlsRequestStreaming(
      {required P2PHost that,
      required String peer,
      required FlutterHlsRequest req}) {
    final sink = RustStreamSink<FlutterHlsStreamEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_box_autoadd_flutter_hls_request(req, serializer);
        sse_encode_StreamSink_flutter_hls_stream_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostSendHlsRequestStreamingConstMeta,
      argValues: [that, peer, req, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateP2PHostSendHlsRequestStreamingConstMeta =>
      const TaskConstMeta(
        debugName: "P2PHost_send_hls_request_streaming",
        argNames: ["that", "peer", "req", "sink"],
      );

  @override
  Future<FlutterPairingResponse> crateP2PHostSendPairingRequest(
      {required P2PHost that,
      required String peer,
      required FlutterPairingRequest req}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            that, serializer);
        sse_encode_String(peer, serializer);
        sse_encode_box_autoadd_flutter_pairing_request(req, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_flutter_pairing_response,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateP2PHostSendPairingRequestConstMeta,
      argValues: [that, peer, req],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateP2PHostSendPairingRequestConstMeta =>
      const TaskConstMeta(
        debugName: "P2PHost_send_pairing_request",
        argNames: ["that", "peer", "req"],
      );

  @override
  Future<void> crateInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  RustArcIncrementStrongCountFnType
      get rust_arc_increment_strong_count_P2PHost => wire
          .rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost;

  RustArcDecrementStrongCountFnType
      get rust_arc_decrement_strong_count_P2PHost => wire
          .rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  P2PHost
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PHostImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  P2PHost
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PHostImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  P2PHost
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return P2PHostImpl.frbInternalDcoDecode(raw as List<dynamic>);
  }

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<FlutterHlsStreamEvent>
      dco_decode_StreamSink_flutter_hls_stream_event_Sse(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FlutterGraphQLRequest dco_decode_box_autoadd_flutter_graph_ql_request(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_graph_ql_request(raw);
  }

  @protected
  FlutterHlsRequest dco_decode_box_autoadd_flutter_hls_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_hls_request(raw);
  }

  @protected
  FlutterHlsResponseHeader dco_decode_box_autoadd_flutter_hls_response_header(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_hls_response_header(raw);
  }

  @protected
  FlutterPairingRequest dco_decode_box_autoadd_flutter_pairing_request(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_flutter_pairing_request(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  FlutterConnectionType dco_decode_flutter_connection_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FlutterConnectionType.values[raw as int];
  }

  @protected
  FlutterGraphQLRequest dco_decode_flutter_graph_ql_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterGraphQLRequest(
      query: dco_decode_String(arr[0]),
      variables: dco_decode_opt_String(arr[1]),
      operationName: dco_decode_opt_String(arr[2]),
      authToken: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  FlutterGraphQLResponse dco_decode_flutter_graph_ql_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlutterGraphQLResponse(
      data: dco_decode_opt_String(arr[0]),
      errors: dco_decode_opt_String(arr[1]),
    );
  }

  @protected
  FlutterHlsRequest dco_decode_flutter_hls_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FlutterHlsRequest(
      sessionId: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      rangeStart: dco_decode_opt_box_autoadd_u_64(arr[2]),
      rangeEnd: dco_decode_opt_box_autoadd_u_64(arr[3]),
      authToken: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  FlutterHlsResponse dco_decode_flutter_hls_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FlutterHlsResponse(
      header: dco_decode_flutter_hls_response_header(arr[0]),
      data: dco_decode_list_prim_u_8_strict(arr[1]),
    );
  }

  @protected
  FlutterHlsResponseHeader dco_decode_flutter_hls_response_header(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5)
      throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return FlutterHlsResponseHeader(
      status: dco_decode_u_16(arr[0]),
      contentType: dco_decode_String(arr[1]),
      contentLength: dco_decode_u_64(arr[2]),
      contentRange: dco_decode_opt_String(arr[3]),
      cacheControl: dco_decode_opt_String(arr[4]),
    );
  }

  @protected
  FlutterHlsStreamEvent dco_decode_flutter_hls_stream_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return FlutterHlsStreamEvent_Header(
          dco_decode_box_autoadd_flutter_hls_response_header(raw[1]),
        );
      case 1:
        return FlutterHlsStreamEvent_Chunk(
          dco_decode_list_prim_u_8_strict(raw[1]),
        );
      case 2:
        return const FlutterHlsStreamEvent_End();
      case 3:
        return FlutterHlsStreamEvent_Error(
          dco_decode_String(raw[1]),
        );
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  FlutterNetworkStats dco_decode_flutter_network_stats(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterNetworkStats(
      connectedPeers: dco_decode_usize(arr[0]),
      relayConnected: dco_decode_bool(arr[1]),
      relayUrl: dco_decode_opt_String(arr[2]),
      peerConnectionType: dco_decode_flutter_connection_type(arr[3]),
    );
  }

  @protected
  FlutterPairingRequest dco_decode_flutter_pairing_request(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FlutterPairingRequest(
      claimCode: dco_decode_String(arr[0]),
      deviceName: dco_decode_String(arr[1]),
      deviceType: dco_decode_String(arr[2]),
      deviceOs: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  FlutterPairingResponse dco_decode_flutter_pairing_response(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FlutterPairingResponse(
      success: dco_decode_bool(arr[0]),
      mediaToken: dco_decode_opt_String(arr[1]),
      accessToken: dco_decode_opt_String(arr[2]),
      deviceToken: dco_decode_opt_String(arr[3]),
      error: dco_decode_opt_String(arr[4]),
      directUrls: dco_decode_list_String(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_list_prim_u_8_strict(raw);
  }

  @protected
  (
    P2PHost,
    String
  ) dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) {
      throw Exception('Expected 2 elements, got ${arr.length}');
    }
    return (
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          arr[0]),
      dco_decode_String(arr[1]),
    );
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  P2PHost
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PHostImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  P2PHost
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PHostImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  P2PHost
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return P2PHostImpl.frbInternalSseDecode(
        sse_decode_usize(deserializer), sse_decode_i_32(deserializer));
  }

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<FlutterHlsStreamEvent>
      sse_decode_StreamSink_flutter_hls_stream_event_Sse(
          SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FlutterGraphQLRequest sse_decode_box_autoadd_flutter_graph_ql_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_graph_ql_request(deserializer));
  }

  @protected
  FlutterHlsRequest sse_decode_box_autoadd_flutter_hls_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_hls_request(deserializer));
  }

  @protected
  FlutterHlsResponseHeader sse_decode_box_autoadd_flutter_hls_response_header(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_hls_response_header(deserializer));
  }

  @protected
  FlutterPairingRequest sse_decode_box_autoadd_flutter_pairing_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_flutter_pairing_request(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  FlutterConnectionType sse_decode_flutter_connection_type(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FlutterConnectionType.values[inner];
  }

  @protected
  FlutterGraphQLRequest sse_decode_flutter_graph_ql_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_query = sse_decode_String(deserializer);
    var var_variables = sse_decode_opt_String(deserializer);
    var var_operationName = sse_decode_opt_String(deserializer);
    var var_authToken = sse_decode_opt_String(deserializer);
    return FlutterGraphQLRequest(
        query: var_query,
        variables: var_variables,
        operationName: var_operationName,
        authToken: var_authToken);
  }

  @protected
  FlutterGraphQLResponse sse_decode_flutter_graph_ql_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_data = sse_decode_opt_String(deserializer);
    var var_errors = sse_decode_opt_String(deserializer);
    return FlutterGraphQLResponse(data: var_data, errors: var_errors);
  }

  @protected
  FlutterHlsRequest sse_decode_flutter_hls_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_rangeStart = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_rangeEnd = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_authToken = sse_decode_opt_String(deserializer);
    return FlutterHlsRequest(
        sessionId: var_sessionId,
        path: var_path,
        rangeStart: var_rangeStart,
        rangeEnd: var_rangeEnd,
        authToken: var_authToken);
  }

  @protected
  FlutterHlsResponse sse_decode_flutter_hls_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_header = sse_decode_flutter_hls_response_header(deserializer);
    var var_data = sse_decode_list_prim_u_8_strict(deserializer);
    return FlutterHlsResponse(header: var_header, data: var_data);
  }

  @protected
  FlutterHlsResponseHeader sse_decode_flutter_hls_response_header(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_status = sse_decode_u_16(deserializer);
    var var_contentType = sse_decode_String(deserializer);
    var var_contentLength = sse_decode_u_64(deserializer);
    var var_contentRange = sse_decode_opt_String(deserializer);
    var var_cacheControl = sse_decode_opt_String(deserializer);
    return FlutterHlsResponseHeader(
        status: var_status,
        contentType: var_contentType,
        contentLength: var_contentLength,
        contentRange: var_contentRange,
        cacheControl: var_cacheControl);
  }

  @protected
  FlutterHlsStreamEvent sse_decode_flutter_hls_stream_event(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        var var_field0 =
            sse_decode_box_autoadd_flutter_hls_response_header(deserializer);
        return FlutterHlsStreamEvent_Header(var_field0);
      case 1:
        var var_field0 = sse_decode_list_prim_u_8_strict(deserializer);
        return FlutterHlsStreamEvent_Chunk(var_field0);
      case 2:
        return const FlutterHlsStreamEvent_End();
      case 3:
        var var_field0 = sse_decode_String(deserializer);
        return FlutterHlsStreamEvent_Error(var_field0);
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  FlutterNetworkStats sse_decode_flutter_network_stats(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_connectedPeers = sse_decode_usize(deserializer);
    var var_relayConnected = sse_decode_bool(deserializer);
    var var_relayUrl = sse_decode_opt_String(deserializer);
    var var_peerConnectionType =
        sse_decode_flutter_connection_type(deserializer);
    return FlutterNetworkStats(
        connectedPeers: var_connectedPeers,
        relayConnected: var_relayConnected,
        relayUrl: var_relayUrl,
        peerConnectionType: var_peerConnectionType);
  }

  @protected
  FlutterPairingRequest sse_decode_flutter_pairing_request(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_claimCode = sse_decode_String(deserializer);
    var var_deviceName = sse_decode_String(deserializer);
    var var_deviceType = sse_decode_String(deserializer);
    var var_deviceOs = sse_decode_opt_String(deserializer);
    return FlutterPairingRequest(
        claimCode: var_claimCode,
        deviceName: var_deviceName,
        deviceType: var_deviceType,
        deviceOs: var_deviceOs);
  }

  @protected
  FlutterPairingResponse sse_decode_flutter_pairing_response(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_mediaToken = sse_decode_opt_String(deserializer);
    var var_accessToken = sse_decode_opt_String(deserializer);
    var var_deviceToken = sse_decode_opt_String(deserializer);
    var var_error = sse_decode_opt_String(deserializer);
    var var_directUrls = sse_decode_list_String(deserializer);
    return FlutterPairingResponse(
        success: var_success,
        mediaToken: var_mediaToken,
        accessToken: var_accessToken,
        deviceToken: var_deviceToken,
        error: var_error,
        directUrls: var_directUrls);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_list_prim_u_8_strict(deserializer));
    } else {
      return null;
    }
  }

  @protected
  (
    P2PHost,
    String
  ) sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_field0 =
        sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
            deserializer);
    var var_field1 = sse_decode_String(deserializer);
    return (var_field0, var_field1);
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as P2PHostImpl).frbInternalSseEncode(move: true), serializer);
  }

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as P2PHostImpl).frbInternalSseEncode(move: false), serializer);
  }

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(
        (self as P2PHostImpl).frbInternalSseEncode(move: null), serializer);
  }

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_String,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_flutter_hls_stream_event_Sse(
      RustStreamSink<FlutterHlsStreamEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_flutter_hls_stream_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_flutter_graph_ql_request(
      FlutterGraphQLRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_graph_ql_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_hls_request(
      FlutterHlsRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_hls_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_hls_response_header(
      FlutterHlsResponseHeader self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_hls_response_header(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_flutter_pairing_request(
      FlutterPairingRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_pairing_request(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_flutter_connection_type(
      FlutterConnectionType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_flutter_graph_ql_request(
      FlutterGraphQLRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.query, serializer);
    sse_encode_opt_String(self.variables, serializer);
    sse_encode_opt_String(self.operationName, serializer);
    sse_encode_opt_String(self.authToken, serializer);
  }

  @protected
  void sse_encode_flutter_graph_ql_response(
      FlutterGraphQLResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.data, serializer);
    sse_encode_opt_String(self.errors, serializer);
  }

  @protected
  void sse_encode_flutter_hls_request(
      FlutterHlsRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_opt_box_autoadd_u_64(self.rangeStart, serializer);
    sse_encode_opt_box_autoadd_u_64(self.rangeEnd, serializer);
    sse_encode_opt_String(self.authToken, serializer);
  }

  @protected
  void sse_encode_flutter_hls_response(
      FlutterHlsResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_flutter_hls_response_header(self.header, serializer);
    sse_encode_list_prim_u_8_strict(self.data, serializer);
  }

  @protected
  void sse_encode_flutter_hls_response_header(
      FlutterHlsResponseHeader self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_16(self.status, serializer);
    sse_encode_String(self.contentType, serializer);
    sse_encode_u_64(self.contentLength, serializer);
    sse_encode_opt_String(self.contentRange, serializer);
    sse_encode_opt_String(self.cacheControl, serializer);
  }

  @protected
  void sse_encode_flutter_hls_stream_event(
      FlutterHlsStreamEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case FlutterHlsStreamEvent_Header(field0: final field0):
        sse_encode_i_32(0, serializer);
        sse_encode_box_autoadd_flutter_hls_response_header(field0, serializer);
      case FlutterHlsStreamEvent_Chunk(field0: final field0):
        sse_encode_i_32(1, serializer);
        sse_encode_list_prim_u_8_strict(field0, serializer);
      case FlutterHlsStreamEvent_End():
        sse_encode_i_32(2, serializer);
      case FlutterHlsStreamEvent_Error(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_String(field0, serializer);
    }
  }

  @protected
  void sse_encode_flutter_network_stats(
      FlutterNetworkStats self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_usize(self.connectedPeers, serializer);
    sse_encode_bool(self.relayConnected, serializer);
    sse_encode_opt_String(self.relayUrl, serializer);
    sse_encode_flutter_connection_type(self.peerConnectionType, serializer);
  }

  @protected
  void sse_encode_flutter_pairing_request(
      FlutterPairingRequest self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.claimCode, serializer);
    sse_encode_String(self.deviceName, serializer);
    sse_encode_String(self.deviceType, serializer);
    sse_encode_opt_String(self.deviceOs, serializer);
  }

  @protected
  void sse_encode_flutter_pairing_response(
      FlutterPairingResponse self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_opt_String(self.mediaToken, serializer);
    sse_encode_opt_String(self.accessToken, serializer);
    sse_encode_opt_String(self.deviceToken, serializer);
    sse_encode_opt_String(self.error, serializer);
    sse_encode_list_String(self.directUrls, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_list_prim_u_8_strict(self, serializer);
    }
  }

  @protected
  void
      sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
          (P2PHost, String) self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
        self.$1, serializer);
    sse_encode_String(self.$2, serializer);
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}

@sealed
class P2PHostImpl extends RustOpaque implements P2PHost {
  // Not to be used by end users
  P2PHostImpl.frbInternalDcoDecode(List<dynamic> wire)
      : super.frbInternalDcoDecode(wire, _kStaticData);

  // Not to be used by end users
  P2PHostImpl.frbInternalSseDecode(BigInt ptr, int externalSizeOnNative)
      : super.frbInternalSseDecode(ptr, externalSizeOnNative, _kStaticData);

  static final _kStaticData = RustArcStaticData(
    rustArcIncrementStrongCount:
        RustLib.instance.api.rust_arc_increment_strong_count_P2PHost,
    rustArcDecrementStrongCount:
        RustLib.instance.api.rust_arc_decrement_strong_count_P2PHost,
    rustArcDecrementStrongCountPtr:
        RustLib.instance.api.rust_arc_decrement_strong_count_P2PHostPtr,
  );

  /// Dial a peer using their EndpointAddr JSON.
  Future<void> dial({required String endpointAddrJson}) => RustLib.instance.api
      .crateP2PHostDial(that: this, endpointAddrJson: endpointAddrJson);

  /// Start streaming events to Flutter.
  Stream<String> eventStream() => RustLib.instance.api.crateP2PHostEventStream(
        that: this,
      );

  /// Get network statistics.
  Future<FlutterNetworkStats> getNetworkStats() =>
      RustLib.instance.api.crateP2PHostGetNetworkStats(
        that: this,
      );

  /// Get this node's EndpointAddr as JSON for sharing.
  Future<String> getNodeAddr() => RustLib.instance.api.crateP2PHostGetNodeAddr(
        that: this,
      );

  /// Send a GraphQL request to a specific peer.
  Future<FlutterGraphQLResponse> sendGraphqlRequest(
          {required String peer, required FlutterGraphQLRequest req}) =>
      RustLib.instance.api
          .crateP2PHostSendGraphqlRequest(that: this, peer: peer, req: req);

  /// Send an HLS request to a specific peer and collect the complete response.
  ///
  /// This is a non-streaming version that collects all chunks into a single buffer.
  /// For large files, consider using the local proxy service instead.
  Future<FlutterHlsResponse> sendHlsRequest(
          {required String peer, required FlutterHlsRequest req}) =>
      RustLib.instance.api
          .crateP2PHostSendHlsRequest(that: this, peer: peer, req: req);

  /// Send an HLS request to a specific peer and stream the response.
  ///
  /// Sends Header, Chunk, and End events via a StreamSink. The stream is
  /// cancelled automatically when the Dart subscription is dropped (sink.add
  /// returns an error).
  Stream<FlutterHlsStreamEvent> sendHlsRequestStreaming(
          {required String peer, required FlutterHlsRequest req}) =>
      RustLib.instance.api.crateP2PHostSendHlsRequestStreaming(
          that: this, peer: peer, req: req);

  /// Send a pairing request to a specific peer.
  Future<FlutterPairingResponse> sendPairingRequest(
          {required String peer, required FlutterPairingRequest req}) =>
      RustLib.instance.api
          .crateP2PHostSendPairingRequest(that: this, peer: peer, req: req);
}
