// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  CrossPlatformFinalizerArg get rust_arc_decrement_strong_count_P2PHostPtr => wire
      ._rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHostPtr;

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  P2PHost
      dco_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw);

  @protected
  P2PHost
      dco_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw);

  @protected
  P2PHost
      dco_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          dynamic raw);

  @protected
  RustStreamSink<String> dco_decode_StreamSink_String_Sse(dynamic raw);

  @protected
  RustStreamSink<FlutterHlsStreamEvent>
      dco_decode_StreamSink_flutter_hls_stream_event_Sse(dynamic raw);

  @protected
  RustStreamSink<FlutterInboundControlRequest>
      dco_decode_StreamSink_flutter_inbound_control_request_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  double dco_decode_box_autoadd_f_32(dynamic raw);

  @protected
  FlutterGraphQLRequest dco_decode_box_autoadd_flutter_graph_ql_request(
      dynamic raw);

  @protected
  FlutterHlsRequest dco_decode_box_autoadd_flutter_hls_request(dynamic raw);

  @protected
  FlutterHlsResponseHeader dco_decode_box_autoadd_flutter_hls_response_header(
      dynamic raw);

  @protected
  FlutterLoadContentRequest dco_decode_box_autoadd_flutter_load_content_request(
      dynamic raw);

  @protected
  FlutterPairingRequest dco_decode_box_autoadd_flutter_pairing_request(
      dynamic raw);

  @protected
  FlutterPlaybackSnapshot dco_decode_box_autoadd_flutter_playback_snapshot(
      dynamic raw);

  @protected
  FlutterRemoteControlRequest
      dco_decode_box_autoadd_flutter_remote_control_request(dynamic raw);

  @protected
  FlutterRemoteControlResponse
      dco_decode_box_autoadd_flutter_remote_control_response(dynamic raw);

  @protected
  FlutterTargetCapabilities dco_decode_box_autoadd_flutter_target_capabilities(
      dynamic raw);

  @protected
  PairingKeys dco_decode_box_autoadd_pairing_keys(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  ClaimPayload dco_decode_claim_payload(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  FlutterConnectionType dco_decode_flutter_connection_type(dynamic raw);

  @protected
  FlutterGraphQLRequest dco_decode_flutter_graph_ql_request(dynamic raw);

  @protected
  FlutterGraphQLResponse dco_decode_flutter_graph_ql_response(dynamic raw);

  @protected
  FlutterHlsRequest dco_decode_flutter_hls_request(dynamic raw);

  @protected
  FlutterHlsResponse dco_decode_flutter_hls_response(dynamic raw);

  @protected
  FlutterHlsResponseHeader dco_decode_flutter_hls_response_header(dynamic raw);

  @protected
  FlutterHlsStreamEvent dco_decode_flutter_hls_stream_event(dynamic raw);

  @protected
  FlutterInboundControlRequest dco_decode_flutter_inbound_control_request(
      dynamic raw);

  @protected
  FlutterLoadContentRequest dco_decode_flutter_load_content_request(
      dynamic raw);

  @protected
  FlutterNetworkStats dco_decode_flutter_network_stats(dynamic raw);

  @protected
  FlutterPairingRequest dco_decode_flutter_pairing_request(dynamic raw);

  @protected
  FlutterPairingResponse dco_decode_flutter_pairing_response(dynamic raw);

  @protected
  FlutterPlaybackSnapshot dco_decode_flutter_playback_snapshot(dynamic raw);

  @protected
  FlutterPlaybackState dco_decode_flutter_playback_state(dynamic raw);

  @protected
  FlutterRemoteControlRequest dco_decode_flutter_remote_control_request(
      dynamic raw);

  @protected
  FlutterRemoteControlResponse dco_decode_flutter_remote_control_response(
      dynamic raw);

  @protected
  FlutterTargetCapabilities dco_decode_flutter_target_capabilities(dynamic raw);

  @protected
  FlutterTrackInfo dco_decode_flutter_track_info(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FlutterTrackInfo> dco_decode_list_flutter_track_info(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  double? dco_decode_opt_box_autoadd_f_32(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  Uint8List? dco_decode_opt_list_prim_u_8_strict(dynamic raw);

  @protected
  PairingKeys dco_decode_pairing_keys(dynamic raw);

  @protected
  (
    P2PHost,
    String
  ) dco_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
      dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  P2PHost
      sse_decode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer);

  @protected
  P2PHost
      sse_decode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer);

  @protected
  P2PHost
      sse_decode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<String> sse_decode_StreamSink_String_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<FlutterHlsStreamEvent>
      sse_decode_StreamSink_flutter_hls_stream_event_Sse(
          SseDeserializer deserializer);

  @protected
  RustStreamSink<FlutterInboundControlRequest>
      sse_decode_StreamSink_flutter_inbound_control_request_Sse(
          SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  double sse_decode_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  FlutterGraphQLRequest sse_decode_box_autoadd_flutter_graph_ql_request(
      SseDeserializer deserializer);

  @protected
  FlutterHlsRequest sse_decode_box_autoadd_flutter_hls_request(
      SseDeserializer deserializer);

  @protected
  FlutterHlsResponseHeader sse_decode_box_autoadd_flutter_hls_response_header(
      SseDeserializer deserializer);

  @protected
  FlutterLoadContentRequest sse_decode_box_autoadd_flutter_load_content_request(
      SseDeserializer deserializer);

  @protected
  FlutterPairingRequest sse_decode_box_autoadd_flutter_pairing_request(
      SseDeserializer deserializer);

  @protected
  FlutterPlaybackSnapshot sse_decode_box_autoadd_flutter_playback_snapshot(
      SseDeserializer deserializer);

  @protected
  FlutterRemoteControlRequest
      sse_decode_box_autoadd_flutter_remote_control_request(
          SseDeserializer deserializer);

  @protected
  FlutterRemoteControlResponse
      sse_decode_box_autoadd_flutter_remote_control_response(
          SseDeserializer deserializer);

  @protected
  FlutterTargetCapabilities sse_decode_box_autoadd_flutter_target_capabilities(
      SseDeserializer deserializer);

  @protected
  PairingKeys sse_decode_box_autoadd_pairing_keys(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  ClaimPayload sse_decode_claim_payload(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  FlutterConnectionType sse_decode_flutter_connection_type(
      SseDeserializer deserializer);

  @protected
  FlutterGraphQLRequest sse_decode_flutter_graph_ql_request(
      SseDeserializer deserializer);

  @protected
  FlutterGraphQLResponse sse_decode_flutter_graph_ql_response(
      SseDeserializer deserializer);

  @protected
  FlutterHlsRequest sse_decode_flutter_hls_request(
      SseDeserializer deserializer);

  @protected
  FlutterHlsResponse sse_decode_flutter_hls_response(
      SseDeserializer deserializer);

  @protected
  FlutterHlsResponseHeader sse_decode_flutter_hls_response_header(
      SseDeserializer deserializer);

  @protected
  FlutterHlsStreamEvent sse_decode_flutter_hls_stream_event(
      SseDeserializer deserializer);

  @protected
  FlutterInboundControlRequest sse_decode_flutter_inbound_control_request(
      SseDeserializer deserializer);

  @protected
  FlutterLoadContentRequest sse_decode_flutter_load_content_request(
      SseDeserializer deserializer);

  @protected
  FlutterNetworkStats sse_decode_flutter_network_stats(
      SseDeserializer deserializer);

  @protected
  FlutterPairingRequest sse_decode_flutter_pairing_request(
      SseDeserializer deserializer);

  @protected
  FlutterPairingResponse sse_decode_flutter_pairing_response(
      SseDeserializer deserializer);

  @protected
  FlutterPlaybackSnapshot sse_decode_flutter_playback_snapshot(
      SseDeserializer deserializer);

  @protected
  FlutterPlaybackState sse_decode_flutter_playback_state(
      SseDeserializer deserializer);

  @protected
  FlutterRemoteControlRequest sse_decode_flutter_remote_control_request(
      SseDeserializer deserializer);

  @protected
  FlutterRemoteControlResponse sse_decode_flutter_remote_control_response(
      SseDeserializer deserializer);

  @protected
  FlutterTargetCapabilities sse_decode_flutter_target_capabilities(
      SseDeserializer deserializer);

  @protected
  FlutterTrackInfo sse_decode_flutter_track_info(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FlutterTrackInfo> sse_decode_list_flutter_track_info(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  double? sse_decode_opt_box_autoadd_f_32(SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  Uint8List? sse_decode_opt_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  PairingKeys sse_decode_pairing_keys(SseDeserializer deserializer);

  @protected
  (
    P2PHost,
    String
  ) sse_decode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
      SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Owned_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer);

  @protected
  void
      sse_encode_Auto_Ref_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer);

  @protected
  void
      sse_encode_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
          P2PHost self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_String_Sse(
      RustStreamSink<String> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_flutter_hls_stream_event_Sse(
      RustStreamSink<FlutterHlsStreamEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_flutter_inbound_control_request_Sse(
      RustStreamSink<FlutterInboundControlRequest> self,
      SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_graph_ql_request(
      FlutterGraphQLRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_hls_request(
      FlutterHlsRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_hls_response_header(
      FlutterHlsResponseHeader self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_load_content_request(
      FlutterLoadContentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_pairing_request(
      FlutterPairingRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_playback_snapshot(
      FlutterPlaybackSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_remote_control_request(
      FlutterRemoteControlRequest self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_remote_control_response(
      FlutterRemoteControlResponse self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_flutter_target_capabilities(
      FlutterTargetCapabilities self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_pairing_keys(
      PairingKeys self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_claim_payload(ClaimPayload self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_connection_type(
      FlutterConnectionType self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_graph_ql_request(
      FlutterGraphQLRequest self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_graph_ql_response(
      FlutterGraphQLResponse self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_hls_request(
      FlutterHlsRequest self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_hls_response(
      FlutterHlsResponse self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_hls_response_header(
      FlutterHlsResponseHeader self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_hls_stream_event(
      FlutterHlsStreamEvent self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_inbound_control_request(
      FlutterInboundControlRequest self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_load_content_request(
      FlutterLoadContentRequest self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_network_stats(
      FlutterNetworkStats self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_pairing_request(
      FlutterPairingRequest self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_pairing_response(
      FlutterPairingResponse self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_playback_snapshot(
      FlutterPlaybackSnapshot self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_playback_state(
      FlutterPlaybackState self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_remote_control_request(
      FlutterRemoteControlRequest self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_remote_control_response(
      FlutterRemoteControlResponse self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_target_capabilities(
      FlutterTargetCapabilities self, SseSerializer serializer);

  @protected
  void sse_encode_flutter_track_info(
      FlutterTrackInfo self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_flutter_track_info(
      List<FlutterTrackInfo> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_f_32(double? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_list_prim_u_8_strict(
      Uint8List? self, SseSerializer serializer);

  @protected
  void sse_encode_pairing_keys(PairingKeys self, SseSerializer serializer);

  @protected
  void
      sse_encode_record_auto_owned_rust_opaque_flutter_rust_bridgefor_generated_rust_auto_opaque_inner_p_2_p_host_string(
          (P2PHost, String) self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  void
      rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
      ptr,
    );
  }

  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHostPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_player_rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost');
  late final _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost =
      _rust_arc_increment_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHostPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();

  void
      rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
    ffi.Pointer<ffi.Void> ptr,
  ) {
    return _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost(
      ptr,
    );
  }

  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHostPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Void>)>>(
          'frbgen_player_rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost');
  late final _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHost =
      _rust_arc_decrement_strong_count_RustOpaque_flutter_rust_bridgefor_generatedRustAutoOpaqueInnerP2pHostPtr
          .asFunction<void Function(ffi.Pointer<ffi.Void>)>();
}
