// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.13.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'lib.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `init_logging`, `run_event_dispatcher`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`, `from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<P2pHost>>
abstract class P2PHost implements RustOpaqueInterface {
  /// Dial a peer using their EndpointAddr JSON.
  Future<void> dial({required String endpointAddrJson});

  /// Start streaming events to Flutter.
  ///
  /// Reads from `generic_event_rx`, not `inner.event_rx` directly: a
  /// dispatcher spawned once in `init` already pulled inbound control
  /// requests out onto their own channel, so subscribing here is *not*
  /// required for `remote_control_stream` to work. See `init` for why that
  /// independence matters.
  Stream<String> eventStream();

  /// Get network statistics.
  Future<FlutterNetworkStats> getNetworkStats();

  /// Get this node's EndpointAddr as JSON for sharing.
  Future<String> getNodeAddr();

  /// Initialize a new P2P host with optional custom relay URL.
  ///
  /// `keypair_bytes` is the node's raw 32-byte Ed25519 secret. A browser has
  /// no filesystem, so it reads the secret out of IndexedDB and hands it in
  /// here. Native passes None and leaves the identity to the core, which is
  /// where it was already decided. A slice of the wrong length is dropped
  /// rather than trusted, which costs a fresh identity but never a
  /// malformed one.
  static (P2PHost, String) init({String? relayUrl, Uint8List? keypairBytes}) =>
      RustLib.instance.api
          .crateP2PHostInit(relayUrl: relayUrl, keypairBytes: keypairBytes);

  /// Stream inbound control requests to Flutter.
  ///
  /// Separate from `event_stream` on purpose: that one is a colon-delimited
  /// string protocol, which cannot carry a structured command. This mirrors
  /// `send_hls_request_streaming`, which is already typed.
  ///
  /// Unlike `send_hls_request_streaming`, this does not depend on
  /// `event_stream` being subscribed to: the `init` dispatcher feeds
  /// `control_rx` independently. Calling only this method, without ever
  /// calling `event_stream()`, is a fully supported way to act as a
  /// control target.
  Stream<FlutterInboundControlRequest> remoteControlStream();

  /// Answer an inbound control request.
  ///
  /// A successful return means the response was *enqueued* on the host's
  /// command channel, not that it reached the wire. Task 1 hit this for
  /// real: a process that exits promptly after this returns can drop an
  /// in-flight response. Callers that need the answer delivered must keep
  /// the host alive until the peer's request completes.
  Future<void> respondToRemoteControl(
      {required String requestId, required FlutterRemoteControlResponse res});

  /// Send a GraphQL request to a specific peer.
  Future<FlutterGraphQLResponse> sendGraphqlRequest(
      {required String peer, required FlutterGraphQLRequest req});

  /// Send an HLS request to a specific peer and collect the complete response.
  ///
  /// This is a non-streaming version that collects all chunks into a single buffer.
  /// For large files, consider using the local proxy service instead.
  Future<FlutterHlsResponse> sendHlsRequest(
      {required String peer, required FlutterHlsRequest req});

  /// Send an HLS request to a specific peer and stream the response.
  ///
  /// Sends Header, Chunk, and End events via a StreamSink. The stream is
  /// cancelled automatically when the Dart subscription is dropped (sink.add
  /// returns an error).
  Stream<FlutterHlsStreamEvent> sendHlsRequestStreaming(
      {required String peer, required FlutterHlsRequest req});

  /// Send a pairing request to a specific peer.
  Future<FlutterPairingResponse> sendPairingRequest(
      {required String peer, required FlutterPairingRequest req});

  /// Send a control command to a peer and await its answer.
  Future<FlutterRemoteControlResponse> sendRemoteControlRequest(
      {required String peer, required FlutterRemoteControlRequest req});
}

/// The decrypted contents of a sealed pairing claim.
class ClaimPayload {
  final String nodeAddr;
  final String instanceId;

  const ClaimPayload({
    required this.nodeAddr,
    required this.instanceId,
  });

  @override
  int get hashCode => nodeAddr.hashCode ^ instanceId.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ClaimPayload &&
          runtimeType == other.runtimeType &&
          nodeAddr == other.nodeAddr &&
          instanceId == other.instanceId;
}

/// Connection type for a peer (relay vs direct) for display in Flutter UI
enum FlutterConnectionType {
  /// Direct peer-to-peer connection
  direct,

  /// Connection via relay server
  relay,

  /// Using both relay and direct paths
  mixed,

  /// No active connection
  none,
  ;
}

/// GraphQL request to send over P2P
class FlutterGraphQLRequest {
  final String query;
  final String? variables;
  final String? operationName;
  final String? authToken;

  /// Base64url-encoded JSON describing what this client can decode. Same
  /// value the HTTP path sends in the X-Mydia-Device-Profile header; the
  /// p2p transport has no headers, so it rides along in the request body.
  final String? deviceProfile;

  const FlutterGraphQLRequest({
    required this.query,
    this.variables,
    this.operationName,
    this.authToken,
    this.deviceProfile,
  });

  @override
  int get hashCode =>
      query.hashCode ^
      variables.hashCode ^
      operationName.hashCode ^
      authToken.hashCode ^
      deviceProfile.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterGraphQLRequest &&
          runtimeType == other.runtimeType &&
          query == other.query &&
          variables == other.variables &&
          operationName == other.operationName &&
          authToken == other.authToken &&
          deviceProfile == other.deviceProfile;
}

/// GraphQL response received over P2P
class FlutterGraphQLResponse {
  final String? data;
  final String? errors;

  const FlutterGraphQLResponse({
    this.data,
    this.errors,
  });

  @override
  int get hashCode => data.hashCode ^ errors.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterGraphQLResponse &&
          runtimeType == other.runtimeType &&
          data == other.data &&
          errors == other.errors;
}

/// HLS request to send over P2P
class FlutterHlsRequest {
  final String sessionId;
  final String path;
  final BigInt? rangeStart;
  final BigInt? rangeEnd;
  final String? authToken;

  const FlutterHlsRequest({
    required this.sessionId,
    required this.path,
    this.rangeStart,
    this.rangeEnd,
    this.authToken,
  });

  @override
  int get hashCode =>
      sessionId.hashCode ^
      path.hashCode ^
      rangeStart.hashCode ^
      rangeEnd.hashCode ^
      authToken.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterHlsRequest &&
          runtimeType == other.runtimeType &&
          sessionId == other.sessionId &&
          path == other.path &&
          rangeStart == other.rangeStart &&
          rangeEnd == other.rangeEnd &&
          authToken == other.authToken;
}

/// HLS stream complete response (non-streaming version)
class FlutterHlsResponse {
  final FlutterHlsResponseHeader header;
  final Uint8List data;

  const FlutterHlsResponse({
    required this.header,
    required this.data,
  });

  @override
  int get hashCode => header.hashCode ^ data.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterHlsResponse &&
          runtimeType == other.runtimeType &&
          header == other.header &&
          data == other.data;
}

/// HLS response header received over P2P
class FlutterHlsResponseHeader {
  final int status;
  final String contentType;
  final BigInt contentLength;
  final String? contentRange;
  final String? cacheControl;

  const FlutterHlsResponseHeader({
    required this.status,
    required this.contentType,
    required this.contentLength,
    this.contentRange,
    this.cacheControl,
  });

  @override
  int get hashCode =>
      status.hashCode ^
      contentType.hashCode ^
      contentLength.hashCode ^
      contentRange.hashCode ^
      cacheControl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterHlsResponseHeader &&
          runtimeType == other.runtimeType &&
          status == other.status &&
          contentType == other.contentType &&
          contentLength == other.contentLength &&
          contentRange == other.contentRange &&
          cacheControl == other.cacheControl;
}

@freezed
sealed class FlutterHlsStreamEvent with _$FlutterHlsStreamEvent {
  const FlutterHlsStreamEvent._();

  const factory FlutterHlsStreamEvent.header(
    FlutterHlsResponseHeader field0,
  ) = FlutterHlsStreamEvent_Header;
  const factory FlutterHlsStreamEvent.chunk(
    Uint8List field0,
  ) = FlutterHlsStreamEvent_Chunk;
  const factory FlutterHlsStreamEvent.end() = FlutterHlsStreamEvent_End;
  const factory FlutterHlsStreamEvent.error(
    String field0,
  ) = FlutterHlsStreamEvent_Error;
}

/// An inbound command with the identifiers needed to answer it.
///
/// `peer` is the dialing node's ID, authenticated by iroh during the handshake.
/// It is what the Dart roster check tests against, and it cannot be forged by
/// the payload.
class FlutterInboundControlRequest {
  final String peer;
  final String requestId;
  final FlutterRemoteControlRequest request;

  const FlutterInboundControlRequest({
    required this.peer,
    required this.requestId,
    required this.request,
  });

  @override
  int get hashCode => peer.hashCode ^ requestId.hashCode ^ request.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterInboundControlRequest &&
          runtimeType == other.runtimeType &&
          peer == other.peer &&
          requestId == other.requestId &&
          request == other.request;
}

class FlutterLoadContentRequest {
  final String mediaItemId;
  final String? episodeId;
  final BigInt positionMs;
  final String? audioTrack;
  final String? subtitleTrack;
  final bool autoplay;

  const FlutterLoadContentRequest({
    required this.mediaItemId,
    this.episodeId,
    required this.positionMs,
    this.audioTrack,
    this.subtitleTrack,
    required this.autoplay,
  });

  @override
  int get hashCode =>
      mediaItemId.hashCode ^
      episodeId.hashCode ^
      positionMs.hashCode ^
      audioTrack.hashCode ^
      subtitleTrack.hashCode ^
      autoplay.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterLoadContentRequest &&
          runtimeType == other.runtimeType &&
          mediaItemId == other.mediaItemId &&
          episodeId == other.episodeId &&
          positionMs == other.positionMs &&
          audioTrack == other.audioTrack &&
          subtitleTrack == other.subtitleTrack &&
          autoplay == other.autoplay;
}

/// Network statistics for display in the UI
class FlutterNetworkStats {
  final BigInt connectedPeers;
  final bool relayConnected;

  /// The relay URL currently in use (extracted from endpoint address)
  final String? relayUrl;

  /// Connection type for the connected peer (relay vs direct)
  final FlutterConnectionType peerConnectionType;

  const FlutterNetworkStats({
    required this.connectedPeers,
    required this.relayConnected,
    this.relayUrl,
    required this.peerConnectionType,
  });

  @override
  int get hashCode =>
      connectedPeers.hashCode ^
      relayConnected.hashCode ^
      relayUrl.hashCode ^
      peerConnectionType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterNetworkStats &&
          runtimeType == other.runtimeType &&
          connectedPeers == other.connectedPeers &&
          relayConnected == other.relayConnected &&
          relayUrl == other.relayUrl &&
          peerConnectionType == other.peerConnectionType;
}

class FlutterPairingRequest {
  final String claimCode;
  final String deviceName;
  final String deviceType;
  final String? deviceOs;

  const FlutterPairingRequest({
    required this.claimCode,
    required this.deviceName,
    required this.deviceType,
    this.deviceOs,
  });

  @override
  int get hashCode =>
      claimCode.hashCode ^
      deviceName.hashCode ^
      deviceType.hashCode ^
      deviceOs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterPairingRequest &&
          runtimeType == other.runtimeType &&
          claimCode == other.claimCode &&
          deviceName == other.deviceName &&
          deviceType == other.deviceType &&
          deviceOs == other.deviceOs;
}

class FlutterPairingResponse {
  final bool success;
  final String? mediaToken;
  final String? accessToken;
  final String? deviceToken;
  final String? error;
  final List<String> directUrls;

  const FlutterPairingResponse({
    required this.success,
    this.mediaToken,
    this.accessToken,
    this.deviceToken,
    this.error,
    required this.directUrls,
  });

  @override
  int get hashCode =>
      success.hashCode ^
      mediaToken.hashCode ^
      accessToken.hashCode ^
      deviceToken.hashCode ^
      error.hashCode ^
      directUrls.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterPairingResponse &&
          runtimeType == other.runtimeType &&
          success == other.success &&
          mediaToken == other.mediaToken &&
          accessToken == other.accessToken &&
          deviceToken == other.deviceToken &&
          error == other.error &&
          directUrls == other.directUrls;
}

class FlutterPlaybackSnapshot {
  final FlutterPlaybackState state;
  final String? mediaItemId;
  final String? episodeId;
  final String title;
  final String? subtitle;
  final String? imageUrl;
  final BigInt positionMs;
  final BigInt durationMs;
  final double? volume;
  final bool muted;
  final List<FlutterTrackInfo> audioTracks;
  final List<FlutterTrackInfo> subtitleTracks;
  final String? selectedAudio;
  final String? selectedSubtitle;
  final FlutterTargetCapabilities capabilities;
  final BigInt sequence;

  const FlutterPlaybackSnapshot({
    required this.state,
    this.mediaItemId,
    this.episodeId,
    required this.title,
    this.subtitle,
    this.imageUrl,
    required this.positionMs,
    required this.durationMs,
    this.volume,
    required this.muted,
    required this.audioTracks,
    required this.subtitleTracks,
    this.selectedAudio,
    this.selectedSubtitle,
    required this.capabilities,
    required this.sequence,
  });

  @override
  int get hashCode =>
      state.hashCode ^
      mediaItemId.hashCode ^
      episodeId.hashCode ^
      title.hashCode ^
      subtitle.hashCode ^
      imageUrl.hashCode ^
      positionMs.hashCode ^
      durationMs.hashCode ^
      volume.hashCode ^
      muted.hashCode ^
      audioTracks.hashCode ^
      subtitleTracks.hashCode ^
      selectedAudio.hashCode ^
      selectedSubtitle.hashCode ^
      capabilities.hashCode ^
      sequence.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterPlaybackSnapshot &&
          runtimeType == other.runtimeType &&
          state == other.state &&
          mediaItemId == other.mediaItemId &&
          episodeId == other.episodeId &&
          title == other.title &&
          subtitle == other.subtitle &&
          imageUrl == other.imageUrl &&
          positionMs == other.positionMs &&
          durationMs == other.durationMs &&
          volume == other.volume &&
          muted == other.muted &&
          audioTracks == other.audioTracks &&
          subtitleTracks == other.subtitleTracks &&
          selectedAudio == other.selectedAudio &&
          selectedSubtitle == other.selectedSubtitle &&
          capabilities == other.capabilities &&
          sequence == other.sequence;
}

enum FlutterPlaybackState {
  idle,
  loading,
  buffering,
  playing,
  paused,
  ended,
  error,
  ;
}

@freezed
sealed class FlutterRemoteControlRequest with _$FlutterRemoteControlRequest {
  const FlutterRemoteControlRequest._();

  const factory FlutterRemoteControlRequest.hello({
    required String controllerName,
    required int protocolVersion,
  }) = FlutterRemoteControlRequest_Hello;
  const factory FlutterRemoteControlRequest.getState() =
      FlutterRemoteControlRequest_GetState;
  const factory FlutterRemoteControlRequest.play() =
      FlutterRemoteControlRequest_Play;
  const factory FlutterRemoteControlRequest.pause() =
      FlutterRemoteControlRequest_Pause;
  const factory FlutterRemoteControlRequest.stop() =
      FlutterRemoteControlRequest_Stop;
  const factory FlutterRemoteControlRequest.seek({
    required BigInt positionMs,
  }) = FlutterRemoteControlRequest_Seek;
  const factory FlutterRemoteControlRequest.setVolume({
    required double level,
  }) = FlutterRemoteControlRequest_SetVolume;
  const factory FlutterRemoteControlRequest.setMute({
    required bool muted,
  }) = FlutterRemoteControlRequest_SetMute;
  const factory FlutterRemoteControlRequest.selectAudioTrack({
    String? id,
  }) = FlutterRemoteControlRequest_SelectAudioTrack;
  const factory FlutterRemoteControlRequest.selectSubtitleTrack({
    String? id,
  }) = FlutterRemoteControlRequest_SelectSubtitleTrack;
  const factory FlutterRemoteControlRequest.nextEpisode() =
      FlutterRemoteControlRequest_NextEpisode;
  const factory FlutterRemoteControlRequest.previousEpisode() =
      FlutterRemoteControlRequest_PreviousEpisode;
  const factory FlutterRemoteControlRequest.loadContent(
    FlutterLoadContentRequest field0,
  ) = FlutterRemoteControlRequest_LoadContent;
}

@freezed
sealed class FlutterRemoteControlResponse with _$FlutterRemoteControlResponse {
  const FlutterRemoteControlResponse._();

  const factory FlutterRemoteControlResponse.welcome({
    required String targetName,
    required int protocolVersion,
    required FlutterTargetCapabilities capabilities,
  }) = FlutterRemoteControlResponse_Welcome;
  const factory FlutterRemoteControlResponse.state(
    FlutterPlaybackSnapshot field0,
  ) = FlutterRemoteControlResponse_State;
  const factory FlutterRemoteControlResponse.accepted() =
      FlutterRemoteControlResponse_Accepted;
  const factory FlutterRemoteControlResponse.notAuthorized() =
      FlutterRemoteControlResponse_NotAuthorized;
  const factory FlutterRemoteControlResponse.notPlaying() =
      FlutterRemoteControlResponse_NotPlaying;
  const factory FlutterRemoteControlResponse.unsupported() =
      FlutterRemoteControlResponse_Unsupported;
  const factory FlutterRemoteControlResponse.error(
    String field0,
  ) = FlutterRemoteControlResponse_Error;
}

class FlutterTargetCapabilities {
  final bool volume;
  final bool trackSelection;
  final bool nextPrevious;

  const FlutterTargetCapabilities({
    required this.volume,
    required this.trackSelection,
    required this.nextPrevious,
  });

  @override
  int get hashCode =>
      volume.hashCode ^ trackSelection.hashCode ^ nextPrevious.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterTargetCapabilities &&
          runtimeType == other.runtimeType &&
          volume == other.volume &&
          trackSelection == other.trackSelection &&
          nextPrevious == other.nextPrevious;
}

class FlutterTrackInfo {
  final String id;
  final String label;
  final String? language;

  const FlutterTrackInfo({
    required this.id,
    required this.label,
    this.language,
  });

  @override
  int get hashCode => id.hashCode ^ label.hashCode ^ language.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FlutterTrackInfo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          label == other.label &&
          language == other.language;
}

/// Keys derived from a pairing claim code.
///
/// Held as an object rather than exposed as two free functions so that Argon2id
/// runs once per pairing attempt. At 64 MiB it costs a few hundred milliseconds
/// on a phone and more in a browser, and the lookup and the open both need it.
class PairingKeys {
  final String code;

  const PairingKeys({
    required this.code,
  });

  /// Derive from a claim code as the user typed it. Case, dashes, and
  /// whitespace are normalized inside the core crate.
  static PairingKeys derive({required String code}) =>
      RustLib.instance.api.cratePairingKeysDerive(code: code);

  /// The relay URL path segment: 64 lowercase hex characters.
  Future<String> lookupKey() => RustLib.instance.api.cratePairingKeysLookupKey(
        that: this,
      );

  /// Open a sealed blob fetched from the relay.
  ///
  /// A failure here is meaningful. A wrong code cannot produce a lookup hit
  /// short of a 256-bit collision, so a blob that fetches but does not open
  /// was altered in storage or in transit.
  Future<ClaimPayload> open({required String sealed}) =>
      RustLib.instance.api.cratePairingKeysOpen(that: this, sealed: sealed);

  @override
  int get hashCode => code.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is PairingKeys &&
          runtimeType == other.runtimeType &&
          code == other.code;
}
