query ReleaseBlacklist {
  releaseBlacklist {
    id
    indexer
    guid
    title
    failureReason
    expiresAt
    insertedAt
  }
}

mutation CreateReleaseBlacklistEntry($input: ReleaseBlacklistInput!) {
  createReleaseBlacklistEntry(input: $input) {
    id
    indexer
    guid
    title
  }
}

mutation DeleteReleaseBlacklistEntry($id: ID!) {
  deleteReleaseBlacklistEntry(id: $id)
}
