import 'dart:async';
import 'dart:math';
import 'dart:typed_data';

import 'package:player/core/p2p/p2p_range_stream.dart';
import 'package:player/native/lib.dart' show FlutterHlsResponseHeader;

/// The byte at [offset] of every generated stream. It varies with the
/// offset, so bytes served from the wrong place do not match by chance.
int fakeByteAt(int offset) => offset % 251;

/// [length] generated bytes starting at [start].
Uint8List fakeBytes(int start, int length) =>
    Uint8List.fromList(List.generate(length, (i) => fakeByteAt(start + i)));

FlutterHlsResponseHeader fakeRangeHeader({
  int status = 206,
  String contentType = 'video/x-matroska',
  required int contentLength,
  String? contentRange,
}) {
  return FlutterHlsResponseHeader(
    status: status,
    contentType: contentType,
    contentLength: BigInt.from(contentLength),
    contentRange: contentRange,
  );
}

/// Polls [condition] until it holds, failing after [timeout].
Future<void> waitUntil(
  bool Function() condition, {
  Duration timeout = const Duration(seconds: 5),
}) async {
  final deadline = DateTime.now().add(timeout);
  while (!condition()) {
    if (DateTime.now().isAfter(deadline)) {
      throw TimeoutException('condition not met within $timeout');
    }
    await Future<void>.delayed(const Duration(milliseconds: 10));
  }
}

/// A scripted [P2pRangeStream] that records how it was pulled and cancelled.
class FakeRangeStream implements P2pRangeStream {
  /// Serves [totalBytes] generated bytes in [chunkBytes] pieces. Once
  /// [stallAfterBytes] have been served, if set, [nextChunk] waits until
  /// cancelled. [pace] delays every chunk, standing in for a link of finite
  /// speed.
  FakeRangeStream({
    required this.header,
    required this.totalBytes,
    this.chunkBytes = 64 * 1024,
    this.stallAfterBytes,
    this.pace = Duration.zero,
  }) : _data = null;

  /// Serves [data] as one chunk.
  FakeRangeStream.fromBytes(this.header, Uint8List data)
      : _data = data,
        totalBytes = data.length,
        chunkBytes = max(data.length, 1),
        stallAfterBytes = null,
        pace = Duration.zero;

  @override
  final FlutterHlsResponseHeader header;
  final int totalBytes;
  final int chunkBytes;
  final int? stallAfterBytes;
  final Duration pace;
  final Uint8List? _data;

  /// Bytes handed out so far.
  int pulledBytes = 0;

  /// How many times [cancel] was called.
  int cancelCount = 0;

  final _cancelled = Completer<void>();

  /// Completes on the first [cancel].
  Future<void> get cancelled => _cancelled.future;

  bool get isCancelled => _cancelled.isCompleted;

  @override
  Future<Uint8List?> nextChunk() async {
    // Real chunks arrive through the event loop, and so do these: a fake
    // that answered in microtasks would starve the sockets under test.
    await Future.any([Future<void>.delayed(pace), cancelled]);
    if (isCancelled || pulledBytes >= totalBytes) return null;

    final stall = stallAfterBytes;
    if (stall != null && pulledBytes >= stall) {
      await cancelled;
      return null;
    }

    final length = min(chunkBytes, totalBytes - pulledBytes);
    final data = _data;
    final chunk = data != null
        ? Uint8List.sublistView(data, pulledBytes, pulledBytes + length)
        : fakeBytes(pulledBytes, length);
    pulledBytes += length;
    return chunk;
  }

  @override
  void cancel() {
    cancelCount++;
    if (!isCancelled) _cancelled.complete();
  }
}
