defmodule MydiaWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :mydia
  use Absinthe.Phoenix.Endpoint

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_mydia_key",
    signing_salt: "aGjwFmlL",
    same_site: "Lax",
    # 30 days in seconds - matches Guardian JWT TTL
    max_age: 30 * 24 * 60 * 60
  ]

  # Enable SQL sandbox for browser-based feature tests (Wallaby)
  # This allows browser requests to participate in the test transaction
  # The plug only activates when sandbox metadata is present in the request
  plug Phoenix.Ecto.SQL.Sandbox

  # Trust X-Forwarded-* headers from reverse proxy (Caddy)
  # This ensures conn.scheme reflects the original HTTPS request
  # Required for OIDC redirect URI validation when behind a proxy
  plug Plug.RewriteOn, [:x_forwarded_host, :x_forwarded_port, :x_forwarded_proto]

  socket "/live", Phoenix.LiveView.Socket,
    websocket: [connect_info: [session: @session_options]],
    longpoll: [connect_info: [session: @session_options]]

  # WebSocket for device reconnection
  socket "/ws", MydiaWeb.UserSocket,
    websocket: true,
    longpoll: false

  # WebSocket for GraphQL subscriptions
  socket "/api/graphql/socket", Absinthe.Phoenix.Socket,
    websocket: true,
    longpoll: false

  # The Flutter web player, ahead of the catch-all below so its cache policy
  # wins for "/player/*".
  #
  # Flutter does not content-hash its web output: every build overwrites
  # `main.dart.js` at the same URL. Plug.Static's default `cache_control_for_etags`
  # is "public", which carries no `max-age` and no `Last-Modified`, so a browser
  # is free to reuse its copy on heuristic freshness alone and never ask whether
  # a newer one exists. An operator upgrading the container then keeps serving
  # the new bundle to clients that go on running the previous one, with no error
  # anywhere: the server answers every query correctly, the old app just never
  # asks for the fields it does not know about. That is how the watch indicators
  # shipped to a browser that kept rendering a build from before them.
  #
  # "no-cache" still stores the entity, it only forbids reusing it without
  # revalidating, which the etag settles with a bodiless 304. The bundle stays
  # in the browser's cache; all it loses is the right to serve it unasked.
  #
  # That revalidation is only cheap because `:etag_generation` hashes the bytes.
  # Plug.Static's default validator is phash2({size, mtime}), and a container
  # image stamps a fresh mtime on every file it ships, so the default would
  # re-download the whole tree on each deploy to discover that canvaskit and
  # the fonts had not changed. See `MydiaWeb.PlayerAssets`.
  #
  # `cache_control_for_vsn_requests` stays "no-cache" because nothing Flutter
  # emits appends "?vsn=", so the immutable default would be a year-long
  # promise made on behalf of a URL that carries no version. Plug.Static skips
  # the etag entirely on that branch, so a stray versioned request costs a full
  # transfer either way; this at least keeps it from being cached under a
  # version that means nothing.
  plug Plug.Static,
    at: "/player",
    from: {:mydia, "priv/static/player"},
    gzip: not code_reloading?,
    cache_control_for_etags: "no-cache",
    cache_control_for_vsn_requests: "no-cache",
    etag_generation: {MydiaWeb.PlayerAssets, :etag, []}

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :mydia,
    gzip: not code_reloading?,
    only: MydiaWeb.static_paths()

  # Serve generated media content (thumbnails, sprites, previews)
  # Files are stored in a configurable directory with content-addressable naming
  # Use Application.compile_env for compile-time configuration or fallback to default
  plug Plug.Static,
    at: "/generated",
    from:
      Application.compile_env(:mydia, :generated_media_path) ||
        Path.join(Application.app_dir(:mydia, "priv"), "generated"),
    gzip: false,
    cache_control_for_etags: "public, max-age=31536000",
    headers: %{"access-control-allow-origin" => "*"}

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
    plug Phoenix.Ecto.CheckRepoStatus, otp_app: :mydia
  end

  plug Phoenix.LiveDashboard.RequestLogger,
    param_key: "request_logger",
    cookie_key: "request_logger"

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug Plug.Session, @session_options

  # CORS support for cross-origin API requests (standalone player, native apps)
  # Must be before the router so OPTIONS preflight requests are handled before authentication
  plug Corsica,
    origins: "*",
    allow_headers: ["content-type", "authorization", "x-request-id"],
    allow_methods: ["GET", "HEAD", "POST", "PUT", "DELETE", "OPTIONS"]

  plug MydiaWeb.Router
end
