#!/usr/bin/env bash
# Assert that generated artifacts still agree with the manifests they came from.
#
# Both halves of this exist because of one day, 2026-08-29. Two Dependabot pull
# requests auto-merged three minutes apart, each bumping a manifest and leaving
# something generated from it behind:
#
#   #612 (18:58Z) raised `base64` to 0.23 in mydia_p2p_core/Cargo.toml without
#   regenerating native/mydia_p2p/Cargo.lock, which still pinned 0.22.1. Every
#   `CI / Nix` run failed for the next five days.
#
#   #613 (19:01Z) raised flutter_rust_bridge to 2.13.0 on both the Dart and Rust
#   side without rerunning codegen, so the committed bindings stayed at 2.12.0.
#   frb compares the two at startup, so `RustLib.init()` threw and every native
#   player build booted to an error screen instead of the app.
#
# Neither pull request was mis-evaluated. The jobs that catch this class,
# `CI / Nix` and `CI / Player E2E`, do not run on pull requests at all, so a
# green rollup was true and meaningless. These checks are the cheap part of
# those jobs, hoisted to where a pull request can see them.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

status=0

fail() {
  echo "FAIL: $*" >&2
  status=1
}

# --- flutter_rust_bridge: the pin and the generated bindings ----------------
#
# Three files carry this version and nothing keeps them in step: the Dart
# package, the Rust crate, and the codegen stamp written into every generated
# file. frb's own `_sanityCheckCodegenVersion` compares the last against the
# runtime at startup, which is a crash rather than a build failure, so it has to
# be asserted here.
dart_pin="$(sed -n 's/^  flutter_rust_bridge: \^\(.*\)$/\1/p' player/pubspec.yaml)"
rust_pin="$(sed -n 's/^flutter_rust_bridge = "=\(.*\)"$/\1/p' player/rust/mydia_player_p2p/Cargo.toml)"
codegen="$(sed -n "s/^  String get codegenVersion => '\(.*\)';$/\1/p" player/lib/native/frb_generated.dart)"

if [ -z "$dart_pin" ] || [ -z "$rust_pin" ] || [ -z "$codegen" ]; then
  fail "could not read a flutter_rust_bridge version" \
    "(pubspec='$dart_pin' cargo='$rust_pin' codegen='$codegen')." \
    "One of these files changed shape; update this check."
elif [ "$dart_pin" != "$rust_pin" ] || [ "$codegen" != "$rust_pin" ]; then
  fail "flutter_rust_bridge versions disagree:
    player/pubspec.yaml                        $dart_pin
    player/rust/mydia_player_p2p/Cargo.toml    $rust_pin
    player/lib/native/frb_generated.dart       $codegen
  Run 'flutter_rust_bridge_codegen generate' in player/ and commit the result.
  Leaving these apart ships a player that cannot start."
fi

# Every generated file carries the same stamp, so a partial regeneration is its
# own failure mode.
for f in player/lib/native/frb_generated.dart \
         player/lib/native/frb_generated.io.dart \
         player/lib/native/frb_generated.web.dart \
         player/lib/native/lib.dart \
         player/rust/mydia_player_p2p/src/frb_generated.rs; do
  stamp="$(sed -n 's/.*@generated by `flutter_rust_bridge`@ \([0-9][0-9.]*[0-9]\)\..*/\1/p' "$f" | head -1)"
  if [ -z "$stamp" ]; then
    fail "$f carries no flutter_rust_bridge codegen stamp."
  elif [ -n "$rust_pin" ] && [ "$stamp" != "$rust_pin" ]; then
    fail "$f was generated by $rust_pin's codegen but says $stamp. Regenerate all bindings together."
  fi
done

# --- Rust lockfiles: resolvable without touching the network ----------------
#
# `--locked` fails when the lock does not already satisfy the manifest, which is
# exactly the state a manifest-only bump leaves behind. The Nix build vendors
# from these locks, so a stale one is a build failure there rather than here.
if command -v cargo >/dev/null 2>&1; then
  for d in native/mydia_p2p native/mydia_subsync plugins/webhook_notifier plugins/simkl_sync; do
    [ -f "$d/Cargo.lock" ] || continue
    if ! err="$(cd "$d" && cargo metadata --locked --format-version 1 2>&1 >/dev/null)"; then
      fail "$d/Cargo.lock does not satisfy its manifest:
$(echo "$err" | sed 's/^/    /' | head -5)
  Run 'cargo metadata' in $d and commit the updated lock."
    fi
  done
else
  echo "note: cargo not on PATH, skipping the lockfile half of this check" >&2
fi

if [ "$status" -eq 0 ]; then
  echo "Generated artifacts agree with their manifests."
fi

exit "$status"
