#!/usr/bin/env bash
# Assert that generated artifacts still agree with the manifests they came from.
#
# Both halves of this exist because of one day, 2026-08-29. Two Dependabot pull
# requests auto-merged three minutes apart, each bumping a manifest and leaving
# something generated from it behind:
#
#   #612 (18:58Z) raised `base64` to 0.23 in mydia_p2p_core/Cargo.toml without
#   regenerating native/mydia_p2p/Cargo.lock, which still pinned 0.22.1. Every
#   `CI / Nix` run failed for the next five days.
#
#   #613 (19:01Z) raised the Rust bridge dependency on both the Dart and the
#   Rust side without rerunning codegen, so the committed bindings kept the
#   older stamp. frb compares the two at startup, so `RustLib.init()` threw and
#   every native player build booted to an error screen instead of the app.
#
# Note for anyone editing the comments here: `Check / Flutter Pin` fails any
# line carrying both that toolchain's name and a version literal, so versions
# are described rather than written out.
#
# Neither pull request was mis-evaluated. The jobs that catch this class,
# `CI / Nix` and `CI / Player E2E`, do not run on pull requests at all, so a
# green rollup was true and meaningless. These checks are the cheap part of
# those jobs, hoisted to where a pull request can see them.
set -euo pipefail

root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$root"

status=0

fail() {
  echo "FAIL: $*" >&2
  status=1
}

# --- flutter_rust_bridge: the pin and the generated bindings ----------------
#
# Three files carry this version and nothing keeps them in step: the Dart
# package, the Rust crate, and the codegen stamp written into every generated
# file. frb's own `_sanityCheckCodegenVersion` compares the last against the
# runtime at startup, which is a crash rather than a build failure, so it has to
# be asserted here.
dart_pin="$(sed -n 's/^  flutter_rust_bridge: \^\(.*\)$/\1/p' player/pubspec.yaml)"
rust_pin="$(sed -n 's/^flutter_rust_bridge = "=\(.*\)"$/\1/p' player/rust/mydia_player_p2p/Cargo.toml)"
codegen="$(sed -n "s/^  String get codegenVersion => '\(.*\)';$/\1/p" player/lib/native/frb_generated.dart)"

if [ -z "$dart_pin" ] || [ -z "$rust_pin" ] || [ -z "$codegen" ]; then
  fail "could not read a flutter_rust_bridge version" \
    "(pubspec='$dart_pin' cargo='$rust_pin' codegen='$codegen')." \
    "One of these files changed shape; update this check."
elif [ "$dart_pin" != "$rust_pin" ] || [ "$codegen" != "$rust_pin" ]; then
  fail "flutter_rust_bridge versions disagree:
    player/pubspec.yaml                        $dart_pin
    player/rust/mydia_player_p2p/Cargo.toml    $rust_pin
    player/lib/native/frb_generated.dart       $codegen
  Run 'flutter_rust_bridge_codegen generate' in player/ and commit the result.
  Leaving these apart ships a player that cannot start."
fi

# Every generated file carries the same stamp, so a partial regeneration is its
# own failure mode.
for f in player/lib/native/frb_generated.dart \
         player/lib/native/frb_generated.io.dart \
         player/lib/native/frb_generated.web.dart \
         player/lib/native/lib.dart \
         player/rust/mydia_player_p2p/src/frb_generated.rs; do
  stamp="$(sed -n 's/.*@generated by `flutter_rust_bridge`@ \([0-9][0-9.]*[0-9]\)\..*/\1/p' "$f" | head -1)"
  if [ -z "$stamp" ]; then
    fail "$f carries no flutter_rust_bridge codegen stamp."
  elif [ -n "$rust_pin" ] && [ "$stamp" != "$rust_pin" ]; then
    fail "$f was generated by $rust_pin's codegen but says $stamp. Regenerate all bindings together."
  fi
done

# --- Rust lockfiles: resolvable without touching the network ----------------
#
# `--locked` fails when the lock does not already satisfy the manifest, which is
# exactly the state a manifest-only bump leaves behind. The Nix build vendors
# from these locks, so a stale one is a build failure there rather than here.
#
# `cargo metadata --locked` still hits the crates.io index to validate the lock.
# On 2026-09-25 a transient index fetch failure on master (`failed to get libc`)
# failed `Check / Generated Freshness` even though every lock was current. Retry
# only errors that look like network or registry outages, not a stale lock.
cargo_lock_err_is_transient() {
  case $1 in
    *"failed to get "*) return 0 ;;
    *"Could not connect"*) return 0 ;;
    *"Connection refused"*) return 0 ;;
    *"timed out"*) return 0 ;;
    *"Temporary failure in name resolution"*) return 0 ;;
  esac
  return 1
}

cargo_metadata_locked() {
  local d=$1 attempts=3 i err=""
  for ((i = 1; i <= attempts; i++)); do
    if err="$(cd "$d" && cargo metadata --locked --format-version 1 2>&1 >/dev/null)"; then
      return 0
    fi
    if [ "$i" -lt "$attempts" ] && cargo_lock_err_is_transient "$err"; then
      echo "note: cargo metadata in $d failed with a transient error (attempt $i/$attempts), retrying..." >&2
      sleep "$((i * 10))"
      continue
    fi
    printf '%s' "$err"
    return 1
  done
}

if command -v cargo >/dev/null 2>&1; then
  # shellcheck source=scripts/lib/cargo-lock-dirs.sh
  source "$root/scripts/lib/cargo-lock-dirs.sh"
  for d in "${cargo_lock_dirs[@]}"; do
    [ -f "$d/Cargo.lock" ] || continue
    if ! err="$(cargo_metadata_locked "$d")"; then
      fail "$d/Cargo.lock does not satisfy its manifest:
$(echo "$err" | sed 's/^/    /' | head -5)
  Run 'cargo metadata' in $d and commit the updated lock."
    fi
  done
else
  echo "note: cargo not on PATH, skipping the lockfile half of this check" >&2
fi

# --- Nix pins and Elixir/asset manifests -------------------------------------
#
# nix/packages/flake-module.nix and deps.nix pin versions and hashes that must
# stay in lockstep with mix.lock and assets/package.json. Because the NixOS VM
# and package tests run on master push only, a mismatch here passes PR CI and
# breaks master CI once merged.
if [ -f nix/packages/flake-module.nix ] && [ -f mix.lock ] && [ -f assets/package.json ]; then
  if command -v python3 >/dev/null 2>&1; then
    if ! err="$(python3 - << 'PYEOF' 2>&1
import re, sys

status = 0

with open("nix/packages/flake-module.nix") as f:
    nix_text = f.read()
with open("mix.lock") as f:
    mix_lock = f.read()
with open("assets/package.json") as f:
    pkg_json = f.read()

fine_pin = re.search(r'fineVersion\s*=\s*"([^"]+)"', nix_text)
fine_lock = re.search(r'"fine":\s*\{:hex,\s*:fine,\s*"([^"]+)"', mix_lock)
if fine_pin and fine_lock and fine_pin.group(1) != fine_lock.group(1):
    print(f"fine version mismatch: nix/packages/flake-module.nix ({fine_pin.group(1)}) != mix.lock ({fine_lock.group(1)})")
    status = 1

wasmex_pin = re.search(r'wasmexVersion\s*=\s*"([^"]+)"', nix_text)
wasmex_lock = re.search(r'"wasmex":\s*\{:hex,\s*:wasmex,\s*"([^"]+)"', mix_lock)
if wasmex_pin and wasmex_lock and wasmex_pin.group(1) != wasmex_lock.group(1):
    print(f"wasmex version mismatch: nix/packages/flake-module.nix ({wasmex_pin.group(1)}) != mix.lock ({wasmex_lock.group(1)})")
    status = 1

tailwind_pin = re.search(r'tailwindVersion\s*=\s*"([^"]+)"', nix_text)
tailwind_pkg = re.search(r'"tailwindcss":\s*"[\^~=]*([^"]+)"', pkg_json)
if tailwind_pin and tailwind_pkg and tailwind_pin.group(1) != tailwind_pkg.group(1):
    print(f"tailwind version mismatch: nix/packages/flake-module.nix ({tailwind_pin.group(1)}) != assets/package.json ({tailwind_pkg.group(1)})")
    status = 1

import os
if os.path.exists("deps.nix"):
    with open("deps.nix") as f:
        deps_nix = f.read()

    mix_deps = {}
    for m in re.finditer(r'"([a-zA-Z0-9_]+)":\s*\{:hex,\s*:[a-zA-Z0-9_]+,\s*"([^"]+)",.*?\"hexpm\",\s*"([^"]+)"\}', mix_lock):
        mix_deps[m.group(1)] = (m.group(2), m.group(3))

    nix_deps = {}
    for m in re.finditer(r'^\s*([a-zA-Z0-9_]+)\s*=\s*build(?:Mix|Rebar3|ErlangMk)\s+rec\s*\{', deps_nix, re.MULTILINE):
        name = m.group(1)
        start = m.end()
        end = deps_nix.find('    };', start)
        block = deps_nix[start:end]
        ver_m = re.search(r'version\s*=\s*"([^"]+)"', block)
        sha_m = re.search(r'sha256\s*=\s*"([^"]+)"', block)
        if ver_m and sha_m:
            nix_deps[name] = (ver_m.group(1), sha_m.group(1))

    missing = set(mix_deps.keys()) - set(nix_deps.keys())
    if missing:
        print(f"deps.nix is missing dependencies from mix.lock: {', '.join(sorted(missing))}")
        status = 1

    mismatches = []
    for k, (m_ver, m_sha) in mix_deps.items():
        if k in nix_deps:
            n_ver, n_sha = nix_deps[k]
            if m_ver != n_ver or m_sha != n_sha:
                mismatches.append(f"{k} (mix.lock {m_ver} vs deps.nix {n_ver})")
    if mismatches:
        print(f"deps.nix version/hash mismatch with mix.lock: {', '.join(mismatches)}")
        status = 1

sys.exit(status)
PYEOF
)"; then
      fail "Nix dependency pins do not match manifests:
$(echo "$err" | sed 's/^/    /')
  Update nix/packages/flake-module.nix or deps.nix to match mix.lock / assets/package.json."
    fi
  fi
fi

# --- Nix npm dependencies: lockfile matches the pinned hash -----------------
#
# When nix is available, assert npmDeps.hash in nix/packages/flake-module.nix
# matches assets/package-lock.json without a full build.
if command -v nix >/dev/null 2>&1; then
  if ! err="$(nix build .#packages.x86_64-linux.default.npmDeps --no-link 2>&1)"; then
    fail "assets/package-lock.json does not match npmDeps.hash in nix/packages/flake-module.nix:
$(echo "$err" | sed 's/^/    /' | tail -5)
  Update npmDeps.hash in nix/packages/flake-module.nix with the 'got:' hash above."
  fi
fi

if [ "$status" -eq 0 ]; then
  echo "Generated artifacts agree with their manifests."
fi

exit "$status"
