#import '../fragments/artwork_fragment.graphql'
#import '../fragments/progress_fragment.graphql'

query HomeScreen($continueWatchingLimit: Int, $recentlyAddedLimit: Int, $upNextLimit: Int) {
  continueWatching(first: $continueWatchingLimit) {
    id
    type
    title
    artwork {
      ...ArtworkFragment
    }
    progress {
      ...ProgressFragment
    }
    showId
    showTitle
    seasonNumber
    episodeNumber
  }

  recentlyAdded(first: $recentlyAddedLimit) {
    id
    type
    title
    year
    artwork {
      ...ArtworkFragment
    }
    addedAt
  }

  upNext(first: $upNextLimit) {
    progressState
    episode {
      id
      seasonNumber
      episodeNumber
      title
      airDate
      thumbnailUrl
      hasFile
    }
    show {
      id
      title
      artwork {
        ...ArtworkFragment
      }
    }
  }

  trending(type: MOVIE) {
    id
    type
    title
    year
    artwork {
      ...ArtworkFragment
    }
  }
}
