#import '../fragments/artwork_fragment.graphql'
#import '../fragments/progress_fragment.graphql'
#import '../fragments/watch_status_fragment.graphql'

query MoviesList($first: Int, $after: String, $category: MediaCategory) {
  movies(first: $first, after: $after, category: $category) {
    edges {
      node {
        id
        title
        year
        overview
        runtime
        genres
        contentRating
        rating
        artwork {
          ...ArtworkFragment
        }
        progress {
          ...ProgressFragment
        }
        watchStatus {
          ...WatchStatusFragment
        }
        isFavorite
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
