#import '../fragments/artwork_fragment.graphql'
#import '../fragments/watch_status_fragment.graphql'

query TvShowsList($first: Int, $after: String, $category: MediaCategory) {
  tvShows(first: $first, after: $after, category: $category) {
    edges {
      node {
        id
        title
        year
        overview
        status
        genres
        contentRating
        rating
        seasonCount
        episodeCount
        artwork {
          ...ArtworkFragment
        }
        watchStatus {
          ...WatchStatusFragment
        }
        isFavorite
        nextEpisode {
          id
          seasonNumber
          episodeNumber
          title
        }
      }
      cursor
    }
    pageInfo {
      hasNextPage
      hasPreviousPage
      startCursor
      endCursor
    }
    totalCount
  }
}
