[package]
name = "mydia-rs-auth"
version.workspace = true
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
bcrypt = "0.16"
argon2 = "0.5"
jsonwebtoken = "9"
dashmap = "6"
sha2 = "0.10"
chrono = { version = "0.4", default-features = false, features = ["serde", "clock"] }
serde.workspace = true
serde_json = "1"
thiserror.workspace = true
tracing.workspace = true
mydia-rs-models = { path = "../models" }

[dev-dependencies]
tokio.workspace = true

[lints]
workspace = true
