//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, StringArray, UuidText};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "albums")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    pub title: String,
    pub artist_id: UuidText,
    pub release_date: Option<Date>,
    pub album_type: Option<String>,
    #[sea_orm(unique)]
    pub musicbrainz_id: Option<String>,
    pub cover_url: Option<String>,
    #[sea_orm(column_type = "Array(ColumnType::Text.into())", nullable)]
    pub genres: Option<StringArray>,
    pub total_tracks: Option<i32>,
    pub total_duration: Option<i32>,
    pub monitored: Option<bool>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
    pub cover_blob: Option<String>,
    pub cover_source: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::artists::Entity",
        from = "Column::ArtistId",
        to = "super::artists::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Artists,
    #[sea_orm(has_many = "super::tracks::Entity")]
    Tracks,
}

impl Related<super::artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artists.def()
    }
}

impl Related<super::tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
