//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use mydia_rs_db::types::{DateTimeSecs, StringArray, UuidText};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "api_keys")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    pub user_id: UuidText,
    pub name: String,
    #[sea_orm(unique)]
    pub key_hash: String,
    pub last_used_at: Option<DateTimeSecs>,
    pub expires_at: Option<DateTimeSecs>,
    pub inserted_at: DateTimeSecs,
    pub key_prefix: Option<String>,
    pub revoked_at: Option<DateTimeSecs>,
    #[sea_orm(column_type = "Array(ColumnType::Text.into())", nullable)]
    pub permissions: Option<StringArray>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
