//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use mydia_rs_db::types::{DateTimeSecs, UuidText};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "book_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    pub book_id: Option<UuidText>,
    pub library_path_id: Option<UuidText>,
    #[sea_orm(unique)]
    pub path: String,
    pub relative_path: Option<String>,
    pub size: Option<i64>,
    pub format: Option<String>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::books::Entity",
        from = "Column::BookId",
        to = "super::books::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Books,
    #[sea_orm(
        belongs_to = "super::library_paths::Entity",
        from = "Column::LibraryPathId",
        to = "super::library_paths::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    LibraryPaths,
}

impl Related<super::books::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Books.def()
    }
}

impl Related<super::library_paths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LibraryPaths.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
