//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, StringArray, UuidText};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "books")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    pub title: String,
    pub author_id: UuidText,
    #[sea_orm(unique)]
    pub isbn: Option<String>,
    #[sea_orm(unique)]
    pub isbn13: Option<String>,
    #[sea_orm(unique)]
    pub openlibrary_id: Option<String>,
    pub goodreads_id: Option<String>,
    pub publish_date: Option<Date>,
    pub publisher: Option<String>,
    pub pages: Option<i32>,
    pub language: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub cover_url: Option<String>,
    #[sea_orm(column_type = "Array(ColumnType::Text.into())", nullable)]
    pub genres: Option<StringArray>,
    pub series_name: Option<String>,
    #[sea_orm(column_type = "Double", nullable)]
    pub series_position: Option<f64>,
    pub monitored: Option<bool>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::authors::Entity",
        from = "Column::AuthorId",
        to = "super::authors::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Authors,
    #[sea_orm(has_many = "super::book_files::Entity")]
    BookFiles,
}

impl Related<super::authors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Authors.def()
    }
}

impl Related<super::book_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookFiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
