//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cardigann_search_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub cardigann_definition_id: Uuid,
    #[sea_orm(column_type = "Text")]
    pub cookies: String,
    pub expires_at: DateTime,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::cardigann_definitions::Entity",
        from = "Column::CardigannDefinitionId",
        to = "super::cardigann_definitions::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    CardigannDefinitions,
}

impl Related<super::cardigann_definitions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardigannDefinitions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
