//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, UuidText};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "cardigann_definitions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    #[sea_orm(unique)]
    pub indexer_id: String,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub language: Option<String>,
    pub r#type: String,
    pub encoding: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub links: String,
    #[sea_orm(column_type = "Text")]
    pub capabilities: String,
    #[sea_orm(column_type = "Text")]
    pub definition: String,
    pub schema_version: String,
    pub enabled: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub config: Option<String>,
    pub last_synced_at: Option<DateTimeSecs>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
    pub health_status: Option<String>,
    pub last_health_check_at: Option<DateTimeSecs>,
    pub last_successful_query_at: Option<DateTimeSecs>,
    pub consecutive_failures: Option<i32>,
    pub flaresolverr_required: Option<bool>,
    pub flaresolverr_enabled: Option<bool>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::cardigann_search_sessions::Entity")]
    CardigannSearchSessions,
}

impl Related<super::cardigann_search_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CardigannSearchSessions.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
