//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "collections")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub r#type: String,
    pub poster_path: Option<String>,
    pub sort_order: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub smart_rules: Option<String>,
    pub visibility: String,
    pub is_system: bool,
    pub position: i32,
    pub user_id: Uuid,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_items::Entity")]
    CollectionItems,
    #[sea_orm(has_many = "super::import_lists::Entity")]
    ImportLists,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::collection_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionItems.def()
    }
}

impl Related<super::import_lists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImportLists.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
