//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "downloads")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub media_item_id: Option<Uuid>,
    pub episode_id: Option<Uuid>,
    pub indexer: Option<String>,
    pub title: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub download_url: Option<String>,
    #[sea_orm(unique_key = "downloads_download_client_download_client_id_index")]
    pub download_client: Option<String>,
    #[sea_orm(unique_key = "downloads_download_client_download_client_id_index")]
    pub download_client_id: Option<String>,
    pub completed_at: Option<DateTime>,
    #[sea_orm(column_type = "Text", nullable)]
    pub error_message: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata: Option<String>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
    pub import_retry_count: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub import_last_error: Option<String>,
    pub import_next_retry_at: Option<DateTime>,
    pub import_failed_at: Option<DateTime>,
    pub library_path_id: Option<Uuid>,
    pub imported_at: Option<DateTime>,
    pub match_status: Option<String>,
    pub last_progress_at: Option<DateTime>,
    pub last_known_bytes: Option<i32>,
    pub bytes_pulled: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::episodes::Entity",
        from = "Column::EpisodeId",
        to = "super::episodes::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Episodes,
    #[sea_orm(
        belongs_to = "super::library_paths::Entity",
        from = "Column::LibraryPathId",
        to = "super::library_paths::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    LibraryPaths,
    #[sea_orm(
        belongs_to = "super::media_items::Entity",
        from = "Column::MediaItemId",
        to = "super::media_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaItems,
}

impl Related<super::episodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Episodes.def()
    }
}

impl Related<super::library_paths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LibraryPaths.def()
    }
}

impl Related<super::media_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
