//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use mydia_rs_db::types::{DateTimeSecs, JsonMap, UuidText};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "download_client_configs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    #[sea_orm(unique)]
    pub name: String,
    pub r#type: String,
    pub enabled: Option<bool>,
    pub priority: Option<i32>,
    pub host: Option<String>,
    pub port: Option<i32>,
    pub use_ssl: Option<bool>,
    pub url_base: Option<String>,
    pub username: Option<String>,
    pub password: Option<String>,
    pub api_key: Option<String>,
    pub category: Option<String>,
    pub download_directory: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub connection_settings: Option<String>,
    pub updated_by_id: Option<UuidText>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
    pub remove_completed: Option<bool>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub categories: Option<JsonMap<serde_json::Value>>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub priority_profile: Option<JsonMap<serde_json::Value>>,
    pub incomplete_grace_minutes: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
