//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "episodes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique_key = "episodes_media_item_id_season_number_episode_number_index")]
    pub media_item_id: Uuid,
    #[sea_orm(unique_key = "episodes_media_item_id_season_number_episode_number_index")]
    pub season_number: i32,
    #[sea_orm(unique_key = "episodes_media_item_id_season_number_episode_number_index")]
    pub episode_number: i32,
    pub title: Option<String>,
    pub air_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata: Option<String>,
    pub monitored: Option<bool>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::downloads::Entity")]
    Downloads,
    #[sea_orm(has_many = "super::media_files::Entity")]
    MediaFiles,
    #[sea_orm(
        belongs_to = "super::media_items::Entity",
        from = "Column::MediaItemId",
        to = "super::media_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaItems,
    #[sea_orm(has_many = "super::playback_progress::Entity")]
    PlaybackProgress,
}

impl Related<super::downloads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Downloads.def()
    }
}

impl Related<super::media_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaFiles.def()
    }
}

impl Related<super::media_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItems.def()
    }
}

impl Related<super::playback_progress::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaybackProgress.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
