//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "error_tracker_errors")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub kind: String,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    #[sea_orm(column_type = "Text")]
    pub source_line: String,
    #[sea_orm(column_type = "Text")]
    pub source_function: String,
    pub status: String,
    #[sea_orm(unique)]
    pub fingerprint: String,
    pub last_occurrence_at: DateTimeSecs,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
    pub muted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::error_tracker_occurrences::Entity")]
    ErrorTrackerOccurrences,
}

impl Related<super::error_tracker_occurrences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ErrorTrackerOccurrences.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
