//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "error_tracker_occurrences")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    #[sea_orm(column_type = "JsonBinary")]
    pub context: Json,
    #[sea_orm(column_type = "Text")]
    pub reason: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub stacktrace: Json,
    pub error_id: i64,
    pub inserted_at: DateTime,
    pub breadcrumbs: Vec<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::error_tracker_errors::Entity",
        from = "Column::ErrorId",
        to = "super::error_tracker_errors::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ErrorTrackerErrors,
}

impl Related<super::error_tracker_errors::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ErrorTrackerErrors.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
