//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, UuidText};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "import_list_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    #[sea_orm(unique_key = "import_list_items_list_tmdb_unique")]
    pub import_list_id: UuidText,
    #[sea_orm(unique_key = "import_list_items_list_tmdb_unique")]
    pub tmdb_id: i32,
    pub title: String,
    pub year: Option<i32>,
    pub poster_path: Option<String>,
    pub status: String,
    pub skip_reason: Option<String>,
    pub discovered_at: DateTimeSecs,
    pub media_item_id: Option<UuidText>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::import_lists::Entity",
        from = "Column::ImportListId",
        to = "super::import_lists::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    ImportLists,
    #[sea_orm(
        belongs_to = "super::media_items::Entity",
        from = "Column::MediaItemId",
        to = "super::media_items::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    MediaItems,
}

impl Related<super::import_lists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImportLists.def()
    }
}

impl Related<super::media_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
