//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "import_lists")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub name: String,
    #[sea_orm(unique_key = "import_lists_type_media_type_index")]
    pub r#type: String,
    #[sea_orm(unique_key = "import_lists_type_media_type_index")]
    pub media_type: String,
    pub enabled: bool,
    pub sync_interval: i32,
    pub auto_add: bool,
    pub monitored: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub config: Option<Json>,
    pub last_synced_at: Option<DateTime>,
    pub sync_error: Option<String>,
    pub quality_profile_id: Option<Uuid>,
    pub library_path_id: Option<Uuid>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
    pub target_collection_id: Option<Uuid>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::collections::Entity",
        from = "Column::TargetCollectionId",
        to = "super::collections::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Collections,
    #[sea_orm(has_many = "super::import_list_items::Entity")]
    ImportListItems,
    #[sea_orm(
        belongs_to = "super::library_paths::Entity",
        from = "Column::LibraryPathId",
        to = "super::library_paths::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    LibraryPaths,
    #[sea_orm(
        belongs_to = "super::quality_profiles::Entity",
        from = "Column::QualityProfileId",
        to = "super::quality_profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    QualityProfiles,
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Collections.def()
    }
}

impl Related<super::import_list_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImportListItems.def()
    }
}

impl Related<super::library_paths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LibraryPaths.def()
    }
}

impl Related<super::quality_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QualityProfiles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
