//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "import_sessions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub user_id: Uuid,
    pub step: String,
    pub status: String,
    pub scan_path: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub session_data: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub scan_stats: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub import_progress: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub import_results: Option<String>,
    pub completed_at: Option<DateTime>,
    pub expires_at: Option<DateTime>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
