//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "indexer_configs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub name: String,
    pub r#type: String,
    pub enabled: Option<bool>,
    pub priority: Option<i32>,
    pub base_url: Option<String>,
    pub api_key: Option<String>,
    pub rate_limit: Option<i32>,
    #[sea_orm(column_type = "Text", nullable)]
    pub connection_settings: Option<String>,
    pub updated_by_id: Option<Uuid>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
    pub env_name: Option<String>,
    pub indexer_ids: Option<Vec<String>>,
    pub categories: Option<Vec<String>>,
    pub min_post_age_minutes: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
