//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, JsonMap, UuidText};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "library_paths")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    #[sea_orm(unique)]
    pub path: String,
    pub r#type: String,
    pub monitored: Option<bool>,
    pub scan_interval: Option<i32>,
    pub last_scan_at: Option<DateTimeSecs>,
    pub last_scan_status: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_scan_error: Option<String>,
    pub quality_profile_id: Option<UuidText>,
    pub updated_by_id: Option<UuidText>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
    pub from_env: bool,
    pub disabled: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub category_paths: Option<JsonMap<serde_json::Value>>,
    pub auto_organize: Option<bool>,
    pub auto_import: Option<bool>,
    pub auto_rename: Option<bool>,
    pub write_nfo: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::adult_files::Entity")]
    AdultFiles,
    #[sea_orm(has_many = "super::book_files::Entity")]
    BookFiles,
    #[sea_orm(has_many = "super::downloads::Entity")]
    Downloads,
    #[sea_orm(has_many = "super::import_lists::Entity")]
    ImportLists,
    #[sea_orm(has_many = "super::media_files::Entity")]
    MediaFiles,
    #[sea_orm(has_many = "super::music_files::Entity")]
    MusicFiles,
    #[sea_orm(
        belongs_to = "super::quality_profiles::Entity",
        from = "Column::QualityProfileId",
        to = "super::quality_profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    QualityProfiles,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UpdatedById",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Users,
}

impl Related<super::adult_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdultFiles.def()
    }
}

impl Related<super::book_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BookFiles.def()
    }
}

impl Related<super::downloads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Downloads.def()
    }
}

impl Related<super::import_lists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImportLists.def()
    }
}

impl Related<super::media_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaFiles.def()
    }
}

impl Related<super::music_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicFiles.def()
    }
}

impl Related<super::quality_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QualityProfiles.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
