//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "media_items")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub r#type: String,
    pub title: String,
    pub original_title: Option<String>,
    pub year: Option<i32>,
    #[sea_orm(unique)]
    pub tmdb_id: Option<i32>,
    pub imdb_id: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata: Option<String>,
    pub monitored: Option<bool>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
    pub quality_profile_id: Option<Uuid>,
    pub category: Option<String>,
    pub category_override: bool,
    pub monitoring_preset: Option<String>,
    pub seasons_refreshed_at: Option<DateTime>,
    #[sea_orm(unique)]
    pub tvdb_id: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_items::Entity")]
    CollectionItems,
    #[sea_orm(has_many = "super::downloads::Entity")]
    Downloads,
    #[sea_orm(has_many = "super::episodes::Entity")]
    Episodes,
    #[sea_orm(has_many = "super::import_list_items::Entity")]
    ImportListItems,
    #[sea_orm(has_many = "super::media_files::Entity")]
    MediaFiles,
    #[sea_orm(has_many = "super::media_requests::Entity")]
    MediaRequests,
    #[sea_orm(has_many = "super::playback_progress::Entity")]
    PlaybackProgress,
    #[sea_orm(
        belongs_to = "super::quality_profiles::Entity",
        from = "Column::QualityProfileId",
        to = "super::quality_profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    QualityProfiles,
    #[sea_orm(has_many = "super::user_favorites::Entity")]
    UserFavorites,
}

impl Related<super::collection_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionItems.def()
    }
}

impl Related<super::downloads::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Downloads.def()
    }
}

impl Related<super::episodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Episodes.def()
    }
}

impl Related<super::import_list_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImportListItems.def()
    }
}

impl Related<super::media_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaFiles.def()
    }
}

impl Related<super::media_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaRequests.def()
    }
}

impl Related<super::playback_progress::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaybackProgress.def()
    }
}

impl Related<super::quality_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QualityProfiles.def()
    }
}

impl Related<super::user_favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFavorites.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
