//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, UuidText};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "media_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    pub media_item_id: Option<UuidText>,
    pub episode_id: Option<UuidText>,
    pub path: Option<String>,
    pub size: Option<i64>,
    pub quality_profile_id: Option<UuidText>,
    pub resolution: Option<String>,
    pub codec: Option<String>,
    pub hdr_format: Option<String>,
    pub audio_codec: Option<String>,
    pub bitrate: Option<i32>,
    pub verified_at: Option<DateTimeSecs>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata: Option<String>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
    pub library_path_id: Option<UuidText>,
    pub relative_path: Option<String>,
    pub cover_blob: Option<String>,
    pub sprite_blob: Option<String>,
    pub vtt_blob: Option<String>,
    pub preview_blob: Option<String>,
    pub phash: Option<String>,
    pub generated_at: Option<DateTimeSecs>,
    pub trashed_at: Option<DateTimeSecs>,
    pub analyzed_at: Option<DateTimeSecs>,
    pub analysis_attempts: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub last_analysis_error: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::episodes::Entity",
        from = "Column::EpisodeId",
        to = "super::episodes::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Episodes,
    #[sea_orm(
        belongs_to = "super::library_paths::Entity",
        from = "Column::LibraryPathId",
        to = "super::library_paths::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    LibraryPaths,
    #[sea_orm(has_one = "super::media_hashes::Entity")]
    MediaHashes,
    #[sea_orm(
        belongs_to = "super::media_items::Entity",
        from = "Column::MediaItemId",
        to = "super::media_items::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MediaItems,
    #[sea_orm(
        belongs_to = "super::quality_profiles::Entity",
        from = "Column::QualityProfileId",
        to = "super::quality_profiles::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    QualityProfiles,
    #[sea_orm(has_many = "super::subtitles::Entity")]
    Subtitles,
    #[sea_orm(has_many = "super::transcode_jobs::Entity")]
    TranscodeJobs,
}

impl Related<super::episodes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Episodes.def()
    }
}

impl Related<super::library_paths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LibraryPaths.def()
    }
}

impl Related<super::media_hashes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaHashes.def()
    }
}

impl Related<super::media_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItems.def()
    }
}

impl Related<super::quality_profiles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::QualityProfiles.def()
    }
}

impl Related<super::subtitles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Subtitles.def()
    }
}

impl Related<super::transcode_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TranscodeJobs.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
