//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "music_files")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub track_id: Option<Uuid>,
    pub library_path_id: Option<Uuid>,
    #[sea_orm(unique)]
    pub path: String,
    pub relative_path: Option<String>,
    pub size: Option<i64>,
    pub bitrate: Option<i32>,
    pub sample_rate: Option<i32>,
    pub codec: Option<String>,
    pub channels: Option<i32>,
    pub duration: Option<i32>,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::library_paths::Entity",
        from = "Column::LibraryPathId",
        to = "super::library_paths::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    LibraryPaths,
    #[sea_orm(
        belongs_to = "super::tracks::Entity",
        from = "Column::TrackId",
        to = "super::tracks::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Tracks,
}

impl Related<super::library_paths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LibraryPaths.def()
    }
}

impl Related<super::tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Tracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
