//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ObanJobState;
use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, JsonMap, StringArray};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "oban_jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub state: ObanJobState,
    #[sea_orm(column_type = "Text")]
    pub queue: String,
    #[sea_orm(column_type = "Text")]
    pub worker: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub args: JsonMap<serde_json::Value>,
    pub errors: Vec<Json>,
    pub attempt: i32,
    pub max_attempts: i32,
    pub inserted_at: DateTimeSecs,
    pub scheduled_at: DateTimeSecs,
    pub attempted_at: Option<DateTimeSecs>,
    pub completed_at: Option<DateTimeSecs>,
    #[sea_orm(column_type = "Array(ColumnType::Text.into())", nullable)]
    pub attempted_by: Option<StringArray>,
    pub discarded_at: Option<DateTimeSecs>,
    pub priority: i32,
    #[sea_orm(column_type = "Array(ColumnType::Text.into())", nullable)]
    pub tags: Option<StringArray>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub meta: Option<JsonMap<serde_json::Value>>,
    pub cancelled_at: Option<DateTimeSecs>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
