//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use super::sea_orm_active_enums::ObanJobState;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "oban_jobs")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub state: ObanJobState,
    #[sea_orm(column_type = "Text")]
    pub queue: String,
    #[sea_orm(column_type = "Text")]
    pub worker: String,
    #[sea_orm(column_type = "JsonBinary")]
    pub args: Json,
    pub errors: Vec<Json>,
    pub attempt: i32,
    pub max_attempts: i32,
    pub inserted_at: DateTime,
    pub scheduled_at: DateTime,
    pub attempted_at: Option<DateTime>,
    pub completed_at: Option<DateTime>,
    pub attempted_by: Option<Vec<String>>,
    pub discarded_at: Option<DateTime>,
    pub priority: i32,
    pub tags: Option<Vec<String>>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub meta: Option<Json>,
    pub cancelled_at: Option<DateTime>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
