//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, UuidText};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "quality_profiles")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    #[sea_orm(unique)]
    pub name: String,
    pub upgrades_allowed: Option<bool>,
    pub upgrade_until_quality: Option<String>,
    #[sea_orm(column_type = "Text")]
    pub qualities: String,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub is_system: Option<bool>,
    pub version: Option<i32>,
    pub source_url: Option<String>,
    pub last_synced_at: Option<DateTimeSecs>,
    #[sea_orm(column_type = "Text", nullable)]
    pub quality_standards: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub metadata_preferences: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub customizations: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::import_lists::Entity")]
    ImportLists,
    #[sea_orm(has_many = "super::library_paths::Entity")]
    LibraryPaths,
    #[sea_orm(has_many = "super::media_files::Entity")]
    MediaFiles,
    #[sea_orm(has_many = "super::media_items::Entity")]
    MediaItems,
}

impl Related<super::import_lists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImportLists.def()
    }
}

impl Related<super::library_paths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LibraryPaths.def()
    }
}

impl Related<super::media_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaFiles.def()
    }
}

impl Related<super::media_items::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaItems.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
