//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use mydia_rs_db::types::{DateTimeMicros, UuidText};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "release_blacklist")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    #[sea_orm(unique_key = "release_blacklist_indexer_guid_unique")]
    pub indexer: String,
    #[sea_orm(unique_key = "release_blacklist_indexer_guid_unique")]
    pub guid: String,
    pub title: String,
    pub failure_reason: String,
    pub expires_at: Option<DateTimeMicros>,
    pub inserted_at: DateTimeMicros,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
