//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "remote_access_config")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    #[sea_orm(unique)]
    pub instance_id: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub static_public_key: Vec<u8>,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub static_private_key_encrypted: Vec<u8>,
    pub enabled: bool,
    pub inserted_at: DateTime,
    pub updated_at: DateTime,
    pub cert_fingerprint: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub relay_token: Option<String>,
    pub direct_urls: Option<Vec<String>>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
