//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use mydia_rs_db::types::{DateTimeSecs, UuidText};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "remote_devices")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    pub device_name: String,
    pub platform: String,
    #[sea_orm(column_type = "VarBinary(StringLen::None)")]
    pub device_static_public_key: Vec<u8>,
    #[sea_orm(unique)]
    pub token_hash: String,
    pub last_seen_at: Option<DateTimeSecs>,
    pub revoked_at: Option<DateTimeSecs>,
    pub user_id: UuidText,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::pairing_claims::Entity")]
    PairingClaims,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::pairing_claims::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PairingClaims.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
