//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use mydia_rs_db::types::{DateTimeSecs, StringArray, UuidText};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "scenes")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    pub title: String,
    pub studio_id: Option<UuidText>,
    pub release_date: Option<Date>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    #[sea_orm(column_type = "Array(ColumnType::Text.into())", nullable)]
    pub performers: Option<StringArray>,
    #[sea_orm(column_type = "Array(ColumnType::Text.into())", nullable)]
    pub tags: Option<StringArray>,
    pub cover_url: Option<String>,
    pub duration: Option<i32>,
    pub monitored: Option<bool>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::adult_files::Entity")]
    AdultFiles,
    #[sea_orm(
        belongs_to = "super::studios::Entity",
        from = "Column::StudioId",
        to = "super::studios::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Studios,
}

impl Related<super::adult_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AdultFiles.def()
    }
}

impl Related<super::studios::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Studios.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
