//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "Enum", db_type = "Enum", enum_name = "oban_job_state")]
pub enum ObanJobState {
    #[sea_orm(string_value = "available")]
    Available,
    #[sea_orm(string_value = "scheduled")]
    Scheduled,
    #[sea_orm(string_value = "executing")]
    Executing,
    #[sea_orm(string_value = "retryable")]
    Retryable,
    #[sea_orm(string_value = "completed")]
    Completed,
    #[sea_orm(string_value = "discarded")]
    Discarded,
    #[sea_orm(string_value = "cancelled")]
    Cancelled,
}
