//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use mydia_rs_db::types::{DateTimeSecs, UuidText};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "search_backoffs")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    #[sea_orm(unique_key = "search_backoffs_resource_unique")]
    pub resource_type: String,
    #[sea_orm(unique_key = "search_backoffs_resource_unique")]
    pub resource_id: UuidText,
    pub season_number: Option<i32>,
    pub failure_count: i32,
    pub last_failure_reason: Option<String>,
    pub next_eligible_at: Option<DateTimeSecs>,
    pub first_failed_at: Option<DateTimeSecs>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
