//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, UuidText};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "studios")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    #[sea_orm(unique)]
    pub name: String,
    pub sort_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub image_url: Option<String>,
    pub website: Option<String>,
    pub founded_year: Option<i32>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::scenes::Entity")]
    Scenes,
}

impl Related<super::scenes::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Scenes.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
