//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, UuidText};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "subtitle_providers")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    #[sea_orm(unique_key = "subtitle_providers_user_id_name_index")]
    pub user_id: UuidText,
    #[sea_orm(unique_key = "subtitle_providers_user_id_name_index")]
    pub name: String,
    pub r#type: String,
    pub enabled: bool,
    pub priority: i32,
    pub username: Option<String>,
    pub password: Option<String>,
    pub api_key: Option<String>,
    pub quota_remaining: Option<i32>,
    pub quota_total: Option<i32>,
    pub quota_reset_at: Option<DateTimeSecs>,
    pub vip_status: Option<bool>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
