//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use sea_orm::entity::prelude::*;
use mydia_rs_db::types::{DateTimeSecs, UuidText};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "tracks")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    pub title: String,
    #[sea_orm(unique_key = "tracks_album_id_disc_number_track_number_index")]
    pub album_id: UuidText,
    pub artist_id: Option<UuidText>,
    #[sea_orm(unique_key = "tracks_album_id_disc_number_track_number_index")]
    pub track_number: Option<i32>,
    #[sea_orm(unique_key = "tracks_album_id_disc_number_track_number_index")]
    pub disc_number: Option<i32>,
    pub duration: Option<i32>,
    #[sea_orm(unique)]
    pub musicbrainz_id: Option<String>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::albums::Entity",
        from = "Column::AlbumId",
        to = "super::albums::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Albums,
    #[sea_orm(
        belongs_to = "super::artists::Entity",
        from = "Column::ArtistId",
        to = "super::artists::Column::Id",
        on_update = "NoAction",
        on_delete = "SetNull"
    )]
    Artists,
    #[sea_orm(has_many = "super::music_files::Entity")]
    MusicFiles,
    #[sea_orm(has_many = "super::playlist_tracks::Entity")]
    PlaylistTracks,
}

impl Related<super::albums::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Albums.def()
    }
}

impl Related<super::artists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Artists.def()
    }
}

impl Related<super::music_files::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MusicFiles.def()
    }
}

impl Related<super::playlist_tracks::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaylistTracks.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
