//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

use mydia_rs_db::types::{DateTimeSecs, UuidText};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, DeriveEntityModel, Serialize, Deserialize)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: UuidText,
    #[sea_orm(unique)]
    pub username: Option<String>,
    #[sea_orm(unique)]
    pub email: Option<String>,
    pub password_hash: Option<String>,
    #[sea_orm(unique)]
    pub oidc_sub: Option<String>,
    pub oidc_issuer: Option<String>,
    pub role: String,
    pub display_name: Option<String>,
    pub avatar_url: Option<String>,
    pub last_login_at: Option<DateTimeSecs>,
    pub inserted_at: DateTimeSecs,
    pub updated_at: DateTimeSecs,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::api_keys::Entity")]
    ApiKeys,
    #[sea_orm(has_many = "super::collections::Entity")]
    Collections,
    #[sea_orm(has_many = "super::config_settings::Entity")]
    ConfigSettings,
    #[sea_orm(has_many = "super::download_client_configs::Entity")]
    DownloadClientConfigs,
    #[sea_orm(has_many = "super::import_sessions::Entity")]
    ImportSessions,
    #[sea_orm(has_many = "super::indexer_configs::Entity")]
    IndexerConfigs,
    #[sea_orm(has_many = "super::library_paths::Entity")]
    LibraryPaths,
    #[sea_orm(has_many = "super::media_server_configs::Entity")]
    MediaServerConfigs,
    #[sea_orm(has_many = "super::pairing_claims::Entity")]
    PairingClaims,
    #[sea_orm(has_many = "super::playback_progress::Entity")]
    PlaybackProgress,
    #[sea_orm(has_many = "super::playlists::Entity")]
    Playlists,
    #[sea_orm(has_many = "super::remote_devices::Entity")]
    RemoteDevices,
    #[sea_orm(has_many = "super::subtitle_providers::Entity")]
    SubtitleProviders,
    #[sea_orm(has_many = "super::transcode_jobs::Entity")]
    TranscodeJobs,
    #[sea_orm(has_many = "super::user_favorites::Entity")]
    UserFavorites,
    #[sea_orm(has_many = "super::user_integrations::Entity")]
    UserIntegrations,
    #[sea_orm(has_one = "super::user_preferences::Entity")]
    UserPreferences,
}

impl Related<super::api_keys::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ApiKeys.def()
    }
}

impl Related<super::collections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Collections.def()
    }
}

impl Related<super::config_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ConfigSettings.def()
    }
}

impl Related<super::download_client_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::DownloadClientConfigs.def()
    }
}

impl Related<super::import_sessions::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ImportSessions.def()
    }
}

impl Related<super::indexer_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::IndexerConfigs.def()
    }
}

impl Related<super::library_paths::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::LibraryPaths.def()
    }
}

impl Related<super::media_server_configs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MediaServerConfigs.def()
    }
}

impl Related<super::pairing_claims::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PairingClaims.def()
    }
}

impl Related<super::playback_progress::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PlaybackProgress.def()
    }
}

impl Related<super::playlists::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Playlists.def()
    }
}

impl Related<super::remote_devices::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::RemoteDevices.def()
    }
}

impl Related<super::subtitle_providers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SubtitleProviders.def()
    }
}

impl Related<super::transcode_jobs::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TranscodeJobs.def()
    }
}

impl Related<super::user_favorites::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserFavorites.def()
    }
}

impl Related<super::user_integrations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserIntegrations.def()
    }
}

impl Related<super::user_preferences::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserPreferences.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
